# xdxtools Analysis Project Configuration
# Generated automatically by: xdxtools create
#
# Edit this file to customize your analysis parameters.
# Then run: xdxtools run --config <this-file>
#

SIDs:
    - sample1
    - sample2
    - sample3
alignment:
    C1: "7"
    C2: "9"
    T1: 0
    T2: 0
engine:
    type: auto
error_rate: 0.2
group_levels: 2
input:
    fastq_dir: /data_center_01/home/zhengyanhua/xdxtools-go/testdata/fastq/test_fastq/
    pdata_file: /data_center_01/home/zhengyanhua/xdxtools-go/testdata/pdata/test_pdata_mixed.csv
jobid: 4a170fb5d802a3724c2f5edee3b258e5a7ca73eb
mode: WGBS
output:
    analysis_dir: userspace/4a170fb5d802a3724c2f5edee3b258e5a7ca73eb/analysis
    config_dir: userspace/4a170fb5d802a3724c2f5edee3b258e5a7ca73eb/config
    data_dir: userspace/4a170fb5d802a3724c2f5edee3b258e5a7ca73eb/data
    log_dir: userspace/4a170fb5d802a3724c2f5edee3b258e5a7ca73eb/log
    project_dir: userspace/4a170fb5d802a3724c2f5edee3b258e5a7ca73eb
    workflow_dir: userspace/4a170fb5d802a3724c2f5edee3b258e5a7ca73eb/workflow
parallel:
    workers: 4
pdx_mode: true
reference:
    genome: human
    genome_anno:
        - human
        - mouse
    genome_fasta:
        - inst/pdx/homo_sapiens/human.fasta
        - inst/pdx/mouse/mouse.fasta
    genome_index:
        - inst/pdx/homo_sapiens/
        - inst/pdx/mouse/
    rnaseq_gtf: ""
    rnaseq_ref: ""
samples:
    - sample1
    - sample2
    - sample3
species1: human
species2: mouse
steps: 3
suffix: _R1.fastq.gz
suffix2: ""
trim:
    read1_3: 0
    read1_5: 0
    read2_3: 0
    read2_5: 0
    seq_deth: 10
trimSeq1:
    - CGATAGATCGGAAGAGC
    - NO_ADAPTER_CAL_USE_DEFAULT
    - TAGCAGATCGGAAGAGC
trimSeq2:
    - CGATAGATCGGAAGAGC
    - NO_ADAPTER_CAL_USE_DEFAULT
    - TAGCAGATCGGAAGAGC
userid: 4a170fb5d802a3724c2f5edee3b258e5a7ca73eb
workflow: BeaverPDX
