Mode: RNASEQ
userid: 3029f4b4a711aaa9e059a2f763c5e966f017b914
jobid: 3029f4b4a711aaa9e059a2f763c5e966f017b914
species: mouse
graft: mouse
host: mouse
suffix: _R1.fastq.gz
suffix2: _R2.fastq.gz
error: 0.2
trimSeq1:
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
trimSeq2:
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
- NO_ADAPTER_CAL_USE_DEFAULT
C1: '7'
C2: '9'
T1: '0'
T2: '0'
genomeFile:
- inst/pdx/homo_sapiens/
- inst/pdx/mouse/
gnome_fasta:
- inst/pdx/homo_sapiens/hg19.fasta
- inst/pdx/mouse/GRCm38.fasta
genomeAnno:
- hg19
- GRCm38
cgGR_gz: inst/hg19/hg19_CpG_sites.gz
CGI: inst/hg19/hg19_cpgIsland.bed
workDir: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914
workflowDir: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow
analysisDir: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/analysis
selfconfig: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/config
qcDir: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/QC
qcDir_before: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/fastqc_raw
qcDir_after: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/fastqc_clean
SID_log: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/log
trimDir: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/trim
bsmapDir: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/bsmap
bsmapDir_bamtmp: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/bsmap/tmp
outDir_mCall: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/mCall
ourDirUmx: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/uxm
outdir_qualimap: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/QC/qualimap
outDir_mhap: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/mhap
RData_folder: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/RData
DMR_folder: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/analysis/DMR
rawDir: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/data
outDir_betaM: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/analysis/betaM
qc_summary: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/QC
logsummary: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/log
uxm_summary: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/analysis/uxm
SIDs:
- SRR8397559
- SRR8397560
- SRR8397561
- SRR8397562
- SRR8397563
- SRR8397564
- SRR8397565
- SRR8397566
- SRR8397567
- SRR8397568
- SRR8397569
- SRR8397570
- SRR8397571
- SRR8397572
- SRR8397573
- SRR8397574
read1_5: 0.0
read1_3: 0.0
read2_5: 0.0
read2_3: 0.0
seq_deth: 10.0
fixed: ''
clubcpg: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/clubcpg
clubcpg_coverage_before: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/clubcpg/clubcpg_coverage_before
clubcpg_model: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/clubcpg/clubcpg_model
clubcpg_coverage_impute: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/clubcpg/clubcpg_coverage_impute
chrs:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chr20
- chr21
- chr22
rnaseq_gtf:
- inst/rnaseq/mouse/mm39.knownGene.gtf
- placeholder
rnaseq_ref:
- inst/rnaseq/mouse/
- placeholder
methrixh5: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/mCall/methrixh5
GCbias: userspace/3029f4b4a711aaa9e059a2f763c5e966f017b914/workflow/QC/GCbias
user_email: 3084989256@qq.com
PDX_pipeline: no
group_levels: 0
