# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("beaverflow_install works", {
  expect_true(inherits(beaverflow_install, "function")) 
})
