# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("beaver_engine_detect works", {
  expect_true(inherits(beaver_engine_detect, "function")) 
})
