# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("use_server_pdata works", {
  expect_true(inherits(use_server_pdata, "function")) 
})
