# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("conflict_network_analysis works", {
  expect_true(inherits(conflict_network_analysis, "function")) 
})
