# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("BeaverGandalf works", {
  expect_true(inherits(BeaverGandalf, "R6ClassGenerator"))
})

test_that("BeaverGandalf has slurm_jobs field", {
  expect_true("slurm_jobs" %in% names(BeaverGandalf$public_fields))
})

test_that("BeaverGandalf has private Slurm helper methods", {
  private_methods <- names(BeaverGandalf$private_methods)
  expect_true(".submit_sbatch_job" %in% private_methods)
  expect_true(".wait_for_job" %in% private_methods)
  expect_true(".wait_for_array" %in% private_methods)
  expect_true(".prepare_sample_configs" %in% private_methods)
  expect_true(".get_failed_samples" %in% private_methods)
  expect_true(".generate_step1_script" %in% private_methods)
  expect_true(".generate_array_script" %in% private_methods)
  expect_true(".generate_checker_script" %in% private_methods)
  expect_true(".run_step_with_retry" %in% private_methods)
})
