# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("update_gandalf works", {
  expect_true(inherits(update_gandalf, "function")) 
})
