# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Run XenofilteR to filter graft vs host reads in bisulfite-seq data
#'
#' This function uses XenofilteR to separate graft (treated) and host (control) reads in bisulfite-seq data.
#' It prepares a list of sample information, sets up the parallel computing parameters, and runs the XenofilteR function.
#'
#' @param filter_root The root directory for filtering output.
#' @param graft The identifier for the graft samples.
#' @param host The identifier for the host samples.
#' @param threads The number of threads to use for parallel processing.
#' @param MM_threshold The mismatch threshold for XenofilteR.
#' @param Unmapped_penalty The penalty for unmapped reads in XenofilteR.
#'
#' @export
beaver_packxenofilter <- function(filter_root, graft, host, threads, MM_threshold, Unmapped_penalty) {
  # Print parameters to confirm
  cat("Filter root:", filter_root, "\n")
  cat("Graft:", graft, "\n")
  cat("Host:", host, "\n")
  cat("Threads:", threads, "\n")

  # Find all report files and extract unique sample names
  samples <- list.files(filter_root, "_val_1_bismark_bt2_PE_report.txt", recursive = TRUE) %>% 
    stringr::str_remove(., "_val_1_bismark_bt2_PE_report.txt") %>% 
    stringr::str_remove(., paste0(host, "/")) %>% 
    stringr::str_remove(., paste0(graft, "/")) %>% 
    unique()
  
  # Create a data frame with sample information
  sample.list <- data.frame(
    samples = samples
  ) %>% 
    dplyr::mutate(Graft = paste0(filter_root, "/", samples, "_fixed_", graft, ".bam")) %>% 
    dplyr::mutate(Host = paste0(filter_root, "/", samples, "_fixed_", host, ".bam")) %>% 
    dplyr::select(-samples)

  # Set up parallel computing parameters
  bp.param <- BiocParallel::SnowParam(workers = as.numeric(threads), type = "SOCK")
  
  # Try to delete the filtered bams directory if it exists
  tryerror <- try(fs::dir_delete(paste0(filter_root, "/Filtered_bams")))

  # Run XenofilteR with the prepared sample list and parameters
  XenofilteR::XenofilteR(sample.list = sample.list, 
                        destination.folder = filter_root, 
                        bp.param = bp.param, output.names = NULL, 
                        MM_threshold = MM_threshold, Unmapped_penalty = Unmapped_penalty)
}
