# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Identify and process unpaired reads from a BAM file
#'
#' This function takes the path to a BAM file, reads the read names, counts their occurrences, and identifies
#' unpaired reads (those that appear only once). It then writes the names of unpaired reads to the same file,
#' and if there are no unpaired reads, it deletes the file.
#'
#' @param readname The file path to the BAM file.
#'
#' @return No return value, but the function modifies the input file or deletes it.
#'
#' @export
beaver_findunpairedread <- function(readname) {
  # Read the BAM file names into a variable
  bam_readnames <- readname
  readnames <- readLines(bam_readnames)
  
  # Count the occurrences of each read name
  readnames <- table(readnames)
  
  # Filter for read names that appear only once
  readnames <- readnames[readnames == 1]
  
  # Extract the names of the unpaired reads
  readnames <- names(readnames)
  
  # Remove any empty names from the list
  readnames <- readnames[readnames != ""]

  # If there are no unpaired reads, delete the BAM file
  if (length(readnames) == 0) {
    fs::file_delete(bam_readnames)
  } else {
    # Otherwise, write the unpaired read names back to the file
    writeLines(readnames, con = bam_readnames)
  }
}
