# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Process Bismark output to extract methylation information and save to a file
#'
#' This function takes Bismark output, filters for methylated cytosines, and extracts relevant information.
#' It then formats the data and writes it to a new file.
#'
#' @param filein The path to the Bismark output file.
#' @param fileout The path to the output file where processed data will be saved.
#'
#' @return The path to the output file.
#'
#' @export
beaver_packbismark <- function(filein, fileout) {
  # Print the output file path to the console
  message(fileout)
  
  # Construct the command to process the Bismark output
  # The command filters for lines where either $4 (methylation count) or $5 (unmethylated count) is greater than 0,
  # then prints the chromosome, start position, end position, methylation level, and strand information.
  # It also replaces '+' with 'F', '-' with 'R', and spaces with tabs.
  command <- glue::glue("awk '($4 > 0) || ($5 > 0) {{print $1\".\"$2,$1,$2,$3,$4+$5,100*$4/($4+$5),100*$5/($4+$5)}}' {filein} | sed 's/+/F/g' | sed 's/-/R/g' | sed 's/[[:space:]]/\\t/g' > {fileout}")
  
  # Execute the system command
  system(command = command)
  
  # Return the path to the output file
  return(fileout)
}
