# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Perform EnrichR analysis using ggetrs and visualize results
#'
#' This function performs gene set enrichment analysis using the EnrichR API via the `ggetrs` Rust tool.
#' It queries the specified pathway database, filters results by p-value, and optionally plots the top enriched pathways.
#' The results are saved in a YAML file and a PDF plot (if requested).
#'
#' @param pathwaydb Character. The name of the pathway database to use (e.g., "KEGG_2021_Human"). Default is "KEGG_2021_Human".
#' @param genes Character vector. The list of gene symbols to be analyzed.
#' @param output Character. The directory or file path to save the enrichment results. If NULL, a default directory "enrichr" will be created. Default is NULL.
#' @param filter_p Numeric. The p-value threshold for filtering significant pathways. Default is 0.05.
#' @param plot Logical. Whether to generate a dot plot of the top enriched pathways. Default is TRUE.
#' @param top Integer. The number of top pathways to display in the plot. Default is 20.
#'
#' @return A data frame containing the filtered enrichment results, including pathway names, p-values, and overlapping genes.
#'
#' @details
#' This function requires the `ggetrs` Rust tool to be installed and accessible via the `cargo` binary.
#' The function will stop if `ggetrs` is not found. The results are saved in a YAML file and optionally plotted using `ggpubr`.
#'
#' @export
beaver_enrichr <- function(pathwaydb = "KEGG_2021_Human",
                           genes,
                           output = NULL,
                           filter_p = 0.05,
                           plot = T,
                           top = 20){
  #/home/yanhuazheng/.cargo/bin/ggetrs enrichr enrichr -l ontology AP2S1 NSD1 RFX3 > enrichresult.yaml
  home <- Sys.getenv("HOME")
  ggetrs <- glue::glue("{home}/.cargo/bin/ggetrs")
  if (!grepl("/.cargo/",ggetrs)){
    stop(">> Rust and cargo is not installed, install rustup first.")
  }
  if (!grepl("ggetrs",ggetrs)){
    stop(">> ggetrs is not install, install it by cargo install ggetrs")
  }
  if (is.null(output)){
    output <- glue::glue("enrichr")
    fs::dir_create(output)
    output <- glue::glue("{output}/enrichr.yaml")
  }else{
    fs::dir_create(output)
    output <- glue::glue("{output}/enrichr.yaml")
  }
  genes <- paste(genes,collapse = " ")
  enrichr_command <- glue::glue("{ggetrs} enrichr enrichr -l {pathwaydb} {genes} > {output}")
  #print(enrichr_command)
  message(glue::glue(">> Quarying EnrichR in {pathwaydb}"))
  message(glue::glue(">> Quarying EnrichR for genes: {genes}"))
  system(command = enrichr_command)
  message(">> Done! convert results...")
  enrichr_list <- yaml::read_yaml(output)
  enrichr_list <- enrichr_list[[1]]
  for (i in 1:length(enrichr_list)){
    enrichr_list[[i]] <- as.data.frame(enrichr_list[[i]])
  }
  enrichr_tbl <- data.table::rbindlist(enrichr_list) %>% 
    as.data.frame() %>% 
    dplyr::filter(pvalue < filter_p)
  npathway <- unique(enrichr_tbl$term_name) %>% 
    length()
  message(glue::glue(">> Filter pvalues < {filter_p}, {npathway} sig pathways found."))
  
  if (npathway > 0){
    message(">> Reshape enrichr_tbl")
    reshape_enrichr_tbl <- enrichr_tbl %>% 
      dplyr::distinct(term_name,.keep_all = T)
    overlap_genes <- enrichr_tbl$overlapping_genes
    names(overlap_genes) <- enrichr_tbl$term_name
    for (i in 1:nrow(reshape_enrichr_tbl)){
      genes <- overlap_genes[names(overlap_genes) %in% reshape_enrichr_tbl$term_name[i]]
      genes <- paste0(genes,collapse = ",")
      reshape_enrichr_tbl$overlapping_genes[i] <- genes
    }
    if (plot){
      message(">> Plotting ...")
      p <- reshape_enrichr_tbl %>% 
        dplyr::mutate(direction = "plot") %>% 
        {
          .[1:top,]
        } %>% 
        dplyr::filter(!is.na(term_name)) %>% 
      ggpubr::ggdotchart(.,  rotate = TRUE,
                         x = "term_name", y = "combined_score",
                         color = "direction",                                # Color by groups
                         palette = c("#00AFBB", "#E7B800", "#FC4E07"), # Custom color palette
                         sorting = "ascending",                       # Sort value in descending order
                         add = "segments",                             # Add segments from y = 0 to dots
                         add.params = list(color = "lightgray", size = 2), # Change segment color and size
                         group = "direction",                                # Order by groups
                         dot.size = 10,                                 # Large dot size
                         label = round(.[["combined_score"]],1),                        # Add mpg values as dot labels
                         font.label = list(color = "white", size = 9, 
                                           vjust = 0.5),               # Adjust label parameters
                         ggtheme = theme_pubr()                        # ggplot2 theme
      )+
        geom_hline(yintercept = 0, linetype = 2, color = "lightgray")
      print(p)
      message(">> Save Plot")
      ggsave(filename = stringr::str_replace(output,".yaml","_plot.pdf"),
             plot = p,
             width = 6.69 * 2,
             height = 4.61* 1.5 )
    }
    return(reshape_enrichr_tbl)
  }else{
    return(enrichr_tbl)
  }
}
