# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Send an email notification using the blastula package
#'
#' This function composes and sends an email notification to inform the recipient that a specific job step has been completed.
#' It utilizes the blastula package for email composition and sending, and requires credentials for authentication.
#'
#' @param jobid The ID of the job being processed.
#' @param step The step number of the job that has been completed.
#' @param send_from The email address to send the notification from. Defaults to "BeaversBot@outlook.com".
#' @param send_to The email address to send the notification to.
#' @param creds_files The file containing the credentials for email authentication.
#'
#' @return The function does not return any value, but it sends an email.
#'
#' @export
beaver_mail <- function(jobid,
                        step,
                        send_from = "BeaversBot@outlook.com",
                        send_to,
                        creds_files){
  date_time <- blastula::add_readable_time()
  email <- blastula::compose_email(
    body = blastula::md(glue::glue(
      "Hello,Dear USERs!
your Job {jobid} is running in the BeaverBoard, and step {step} is done!

Best wishes,

BeaverBoard Team.
")),
    footer = blastula::md(glue::glue("Email sent on {date_time}."))
  )
  email %>% 
    blastula::smtp_send(
      to = send_to,
      from = send_from,
      subject = glue::glue("Process Report : step {step} is done."),
      credentials = creds_file(creds_files)
    )
}
