# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' BeaverGandalf: A Workflow Manager for Bioinformatics Pipelines
#'
#' This R6 class manages and orchestrates bioinformatics workflows, including
#' data processing, quality control, and analysis. It supports multiple modes
#' (e.g., RRBS, BSseq, RNAseq) and can handle PDX (Patient-Derived Xenograft)
#' pipelines. The class is designed to work with Snakemake workflows and can
#' run on different computing environments (e.g., Kubernetes, Slurm).
#' @field Mode The mode of the pipeline (e.g., "RRBS", "BSSEQ", "RNASEQ").
#' @field species The species being analyzed (e.g., "human", "mouse").
#' @field species1 species1
#' @field species2  species2
#' @field host host
#' @field cgGR_gz cgGR_gz
#' @field qcDir_before qcDir_before
#' @field qcDir_after qcDir_after
#' @field bsmapDir_bamtmp bsmapDir_bamtmp
#' @field samples A vector of sample IDs.
#' @field uploadfile A data frame containing file paths and names.11
#' @field run_log A vector storing runtime logs.
#' @field init_log A vector storing initialization logs.
#' @field yaml_file The path to the YAML configuration file.
#' @field userid A unique user ID for the workflow.
#' @field user_email The email address for notifications.
#' @field PDX_pipeline A logical indicating whether PDX mode is enabled.
#' @field fastqDir The directory for FASTQ files.
#' @field adapter1 Adapter sequences for trimming.
#' @field adapter2 Adapter sequences for trimming
#' @field CGI Paths to reference data files (e.g., CpG sites, CGI).
#' @field genomeFile Paths to genome files.
#' @field gnome_fasta Paths to genome files.
#' @field rnaseq_gtf Paths to RNAseq reference files.
#' @field rnaseq_ref Paths to RNAseq reference files.
#' @field workflow_endpoint workflow endpoint.
#' @field chrs A vector of chromosome names.
#' @field read1_5 Read trimming parameters.
#' @field read1_3 Read trimming parameters.
#' @field read2_5 Read trimming parameters.
#' @field read2_3 Read trimming parameters.
#' @field seq_deth Sequencing depth.
#' @field fixed A string indicating fixed parameters.
#' @field suffix1 Suffixes for FASTQ files.
#' @field suffix2 Suffixes for FASTQ files.
#' @field error Error rate for alignment.
#' @field C1 Alignment parameters.
#' @field C2 Alignment parameters.
#' @field T1 Alignment parameters.
#' @field T2 Alignment parameters.
#' @field graft, host Graft and host species for PDX pipelines.
#' @field pdata Phenotype data.
#' @field workflowDir  Directories for workflow, analysis, and QC.
#' @field analysisDir  Directories for workflow, analysis, and QC.
#' @field qcDir Directories for workflow, analysis, and QC.
#' @field selfconfig The directory for self-generated configuration files.
#' @field SID_log The directory for log files.
#' @field trimDir Directories for trimming, BSMAP, and methylation calling.
#' @field bsmapDir Directories for trimming, BSMAP, and methylation calling.
#' @field outDir_mCall Directories for methylation calling.
#' @field ourDirUmx Directories for UMX and Qualimap results.
#' @field outdir_qualimap Directories for UMX and Qualimap results.
#' @field outDir_mhap Directories for M-HAP and RData files.
#' @field RData_folder Directories for M-HAP and RData files.
#' @field clubcpg Directories for CpG data.
#' @field clubcpg_coverage_before Directories for CpG data.
#' @field clubcpg_model Directories for CpG data.
#' @field clubcpg_coverage_impute Directory for imputed CpG coverage.
#' @field qc_summary Directories for QC summaries and log summaries.
#' @field logsummary Directories for QC summaries and log summaries.
#' @field outDir_betaM Directories for betaM, UXM summary, and DMR results.
#' @field uxm_summary Directories for betaM, UXM summary, and DMR results.
#' @field DMR_folder Directories for betaM, UXM summary, and DMR results.
#' @field methrixh5 Directories for methrix H5 and GC bias results.
#' @field GCbias Directories for methrix H5 and GC bias results.
#' @field userspace The root directory for user workflows.
#' @field genomeAnno the shortname of Genomes used in the BSseq Pipelines
#' @field group_levels the num of group_levels
#' @field slurm_jobs A data frame tracking Slurm job submissions (job_id, script, status, submit_time, end_time). Only populated in Slurm mode.
#' @method initialize initialize
#' @method gandalf_info gandalf_info
#' @method gandalf_fastq_move gandalf_fastq_move
#' @method gandalf_create_filework gandalf_create_filework
#' @method gandalf_make_config gandalf_make_config
#' @method gandalf2wars gandalf2wars
#' @method gandalf_aggResult gandalf_aggResult
#' @method gandalf_process_discovery gandalf_process_discovery
#
#' @export
BeaverGandalf <- R6::R6Class(
  "BeaverGandalf",
  public = list(
    Mode = NULL,
    suffix1 = "_R1_fastq.gz",
    suffix2 = NULL,
    error = 0.2,
    adapter1 = "AGATCGGAAGAGC",
    adapter2 = "AGATCGGAAGAGC",
    C1 = "7",
    C2 = "9",
    T1 = 0,
    T2 = 0,
    species = NULL,
    species1 = "human",
    species2 = NULL,
    graft = "human",
    host = NULL,
    read1_5 = 0,
    read1_3 = 0,
    read2_5 = 0,
    read2_3 = 0,
    seq_deth = 10,
    pdata = NULL,
    uploadfile = NULL,
    samples = NULL,
    workflow_endpoint = NULL,
    userid = NULL,
    fixed = NULL,
    yaml_file = NULL,
    #cgGR = "inst/hg19/hg19_CpG_sites.RData",
    cgGR_gz = "inst/hg19/hg19_CpG_sites.gz",
    CGI = "inst/hg19/hg19_cpgIsland.bed",
    gnome_fasta = c(
      "inst/pdx/homo_sapiens/hg19.fasta",
      "inst/pdx/mouse/GRCm38.fasta"
    ),
    genomeFile = c("inst/pdx/homo_sapiens/", "inst/pdx/mouse/"),
    genomeAnno = c("hg19", "GRCm38"),
    rnaseq_gtf = "inst/rnaseq/homo_sapiens/hg19.ensGene_sorted.gtf",
    rnaseq_ref = "inst/rnaseq/homo_sapiens/",
    #CGIRData = "inst/hg19/hg19_CGI_GR.RData",
    #CCGG = "inst/hg19/CCGG.RData",
    #CpG  = "inst/hg19/hg19_CpG_sites.RData",
    #hg19_genomeFile = "inst/hg19/ucsc_hg19-20180821.fa",
    workflowDir = "/workflow",
    analysisDir = "/analysis",
    selfconfig = "/config",
    qcDir = "/QC",
    qcDir_before = "/fastqc_raw",
    qcDir_after = "/fastqc_clean",
    SID_log = "/log",
    trimDir = "/trim",
    bsmapDir = "/bsmap",
    bsmapDir_bamtmp = "/bsmap/tmp",
    outDir_mCall = "/mCall",
    ourDirUmx = "/uxm",
    outdir_qualimap = "/QC/qualimap",
    outDir_mhap = "/mhap",
    RData_folder = "/RData",
    clubcpg = "/clubcpg",
    clubcpg_coverage_before = "/clubcpg/clubcpg_coverage_before",
    clubcpg_model = "/clubcpg/clubcpg_model",
    clubcpg_coverage_impute = "/clubcpg/clubcpg_coverage_impute",
    qc_summary = "/QC",
    logsummary = "/log",
    outDir_betaM = "/betaM",
    uxm_summary = "/uxm",
    DMR_folder = "/DMR",
    methrixh5 = "/methrixh5",
    GCbias = "/GCbias",
    chrs = NULL,
    userspace = "userspace",
    fastqDir = NULL,
    PDX_pipeline = NULL,
    user_email = NULL,
    init_log = NULL,
    run_log = NULL,
    group_levels = NULL,
    slurm_jobs = NULL, # data.frame to track Slurm job submissions

    #' @param Mode \code{character} The mode of the pipeline (e.g., "RRBS", "BSSEQ", "RNASEQ").
    #' @param suffix1 \code{character} Suffix for the first read of paired-end FASTQ files (default: "_R1.fastq.gz").
    #' @param suffix2 \code{character} Suffix for the second read of paired-end FASTQ files (default: NULL).
    #' @param error \code{numeric} Error rate for alignment (default: 0.2).
    #' @param adapter1 \code{character} Adapter sequence for the first read (default: "AGATCGGAAGAGC").
    #' @param adapter2 \code{character} Adapter sequence for the second read (default: "AGATCGGAAGAGC").
    #' @param C1 \code{numeric} Alignment parameters (default: 0).
    #' @param C2 \code{numeric} Alignment parameters (default: 0).
    #' @param T1 \code{numeric} Alignment parameters (default: 0).
    #' @param T2 \code{numeric} Alignment parameters (default: 0).
    #' @param species \code{character} or \code{NULL} Species being analyzed (default: NULL).
    #' @param species1 \code{character} Primary species (default: "human").
    #' @param species2 \code{character} Secondary species (default: NULL).
    #' @param graft \code{character} Graft species for PDX pipelines (default: "human").
    #' @param host \code{character} Host species for PDX pipelines (default: NULL).
    #' @param read1_5 \code{numeric} Read trimming parameters (default: 0).
    #' @param read1_3 \code{numeric} Read trimming parameters (default: 0).
    #' @param read2_5 \code{numeric} Read trimming parameters (default: 0).
    #' @param read2_3 \code{numeric} Read trimming parameters (default: 0).
    #' @param seq_deth \code{numeric} Sequencing depth (default: 10).
    #' @param pdata \code{data.frame} or \code{NULL} Phenotype data (default: NULL).
    #' @param uploadfile \code{data.frame} or \code{NULL} Data frame containing file paths and names (default: NULL).
    #' @param samples \code{character} or \code{NULL} Sample IDs (default: NULL).
    #' @param workflow_endpoint \code{character} or \code{NULL} Workflow endpoint configuration (default: NULL).
    #' @param userid \code{character} or \code{NULL} Unique user ID (default: NULL).
    #' @param fixed \code{character} or \code{NULL} Fixed parameters string (default: NULL).
    #' @param yaml_file \code{character} or \code{NULL} Path to the YAML configuration file (default: NULL).
    #' @param cgGR_gz \code{character} or \code{NULL} Gzipped version of cgGR (default: NULL).
    #' @param CGI \code{character} Path to CpG islands BED file (default: "inst/hg19/hg19_cpgIsland.bed").
    #' @param gnome_fasta \code{character} or \code{vector} Path(s) to genome FASTA files (default: hg19 and GRCm38).
    #' @param genomeFile \code{character} or \code{vector} Path(s) to genome files (default: hg19 and GRCm38).
    #' @param rnaseq_gtf \code{character} Path to RNAseq GTF file (default: "inst/rnaseq/homo_sapiens/hg19.ensGene_sorted.gtf").
    #' @param rnaseq_ref \code{character} Path to RNAseq reference directory (default: "inst/rnaseq/homo_sapiens/").
    #' @param fastqDir \code{character} Directory for FASTQ files (default: "/data").
    #' @param workflowDir \code{character} Directory for workflow files (default: "/workflow").
    #' @param analysisDir \code{character} Directory for analysis results (default: "/analysis").
    #' @param selfconfig \code{character} Directory for self-generated configuration files (default: "/config").
    #' @param qcDir \code{character} Directory for quality control results (default: "/QC").
    #' @param qcDir_before \code{character} Directory for raw QC results (default: "/fastqc_raw").
    #' @param qcDir_after \code{character} Directory for cleaned QC results (default: "/fastqc_clean").
    #' @param SID_log \code{character} Directory for log files (default: "/log").
    #' @param trimDir \code{character} Directory for trimmed files (default: "/trim").
    #' @param bsmapDir \code{character} Directory for BSMAP results (default: "/bsmap").
    #' @param bsmapDir_bamtmp \code{character} Temporary directory for BSMAP BAM files (default: "/bsmap/tmp").
    #' @param outDir_mCall \code{character} Directory for methylation calling results (default: "/mCall").
    #' @param ourDirUmx \code{character} Directory for UMX results (default: "/uxm").
    #' @param outdir_qualimap \code{character} Directory for Qualimap results (default: "/QC/qualimap").
    #' @param outDir_mhap \code{character} Directory for M-HAP results (default: "/mhap").
    #' @param RData_folder \code{character} Directory for RData files (default: "/RData").
    #' @param clubcpg \code{character} Directory for CpG data (default: "/clubcpg").
    #' @param clubcpg_coverage_before \code{character} Directory for pre-imputation CpG coverage (default: "/clubcpg/clubcpg_coverage_before").
    #' @param clubcpg_model \code{character} Directory for CpG models (default: "/clubcpg/clubcpg_model").
    #' @param clubcpg_coverage_impute \code{character} Directory for imputed CpG coverage (default: "/clubcpg/clubcpg_coverage_impute").
    #' @param qc_summary \code{character} Directory for QC summaries (default: "/QC").
    #' @param logsummary \code{character} Directory for log summaries (default: "/log").
    #' @param outDir_betaM \code{character} Directory for betaM results (default: "/betaM").
    #' @param uxm_summary \code{character} Directory for UXM summaries (default: "/uxm").
    #' @param DMR_folder \code{character} Directory for DMR results (default: "/DMR").
    #' @param methrixh5 \code{character} Directory for methrix H5 files (default: "/methrixh5").
    #' @param GCbias \code{character} Directory for GC bias results (default: "/GCbias").
    #' @param chrs \code{character} or \code{NULL} Chromosome names (default: NULL).
    #' @param userspace \code{character} Root directory for user workflows (default: "userspace").
    #' @param PDX_pipeline \code{logical} or \code{NULL} Whether to enable PDX pipeline mode (default: NULL).
    #' @param init_log \code{character} or \code{NULL} Initialization log (default: NULL).
    #' @param user_email \code{character} User email for notifications (default: "whoami").
    #' @param new_userid_always \code{logical} Whether to always generate a new user ID (default: TRUE).
    #' @param genomeAnno the shortname of Genomes used in the BSseq Pipelines ,default:c("hg19","GRCm38")
    #'
    #' @return An initialized BeaverGandalf object.
    #' @export
    initialize = function(
      Mode = NULL,
      suffix1 = "_R1.fastq.gz",
      suffix2 = NULL,
      error = 0.2,
      adapter1 = "AGATCGGAAGAGC",
      adapter2 = "AGATCGGAAGAGC",
      C1 = "0",
      C2 = "0",
      T1 = "0",
      T2 = "0",
      species = NULL,
      species1 = "human",
      species2 = NULL,
      graft = "human",
      host = NULL,
      read1_5 = 0,
      read1_3 = 0,
      read2_5 = 0,
      read2_3 = 0,
      seq_deth = 10,
      pdata = NULL,
      uploadfile = NULL,
      samples = NULL,
      workflow_endpoint = NULL,
      userid = NULL,
      fixed = NULL,
      yaml_file = NULL,
      #cgGR = "inst/hg19/hg19_CpG_sites.RData",
      cgGR_gz = "inst/hg19/hg19_CpG_sites.gz",
      CGI = "inst/hg19/hg19_cpgIsland.bed",
      gnome_fasta = c(
        "inst/pdx/homo_sapiens/hg19.fasta",
        "inst/pdx/mouse/GRCm38.fasta"
      ),
      genomeFile = c("inst/pdx/homo_sapiens/", "inst/pdx/mouse/"),
      genomeAnno = c("hg19", "GRCm38"),
      rnaseq_gtf = "inst/rnaseq/homo_sapiens/hg19.ensGene_sorted.gtf",
      rnaseq_ref = "inst/rnaseq/homo_sapiens/",
      fastqDir = "/data",
      workflowDir = "/workflow",
      analysisDir = "/analysis",
      selfconfig = "/config",
      qcDir = "/QC",
      qcDir_before = "/fastqc_raw",
      qcDir_after = "/fastqc_clean",
      SID_log = "/log",
      trimDir = "/trim",
      bsmapDir = "/bsmap",
      bsmapDir_bamtmp = "/bsmap/tmp",
      outDir_mCall = "/mCall",
      ourDirUmx = "/uxm",
      outdir_qualimap = "/QC/qualimap",
      outDir_mhap = "/mhap",
      RData_folder = "/RData",
      clubcpg = "/clubcpg",
      clubcpg_coverage_before = "/clubcpg/clubcpg_coverage_before",
      clubcpg_model = "/clubcpg/clubcpg_model",
      clubcpg_coverage_impute = "/clubcpg/clubcpg_coverage_impute",
      qc_summary = "/QC",
      logsummary = "/log",
      outDir_betaM = "/betaM",
      uxm_summary = "/uxm",
      DMR_folder = "/DMR",
      methrixh5 = "/methrixh5",
      GCbias = "/GCbias",
      chrs = NULL,
      userspace = "userspace",
      PDX_pipeline = NULL,
      init_log = NULL,
      user_email = "whoami",
      new_userid_always = T
    ) {
      # 一些不需要计算的静态配置
      message(">> Configure pipeline ...")
      init_log <- c(">> Configure pipeline ...")
      if (species1 == "homo_sapiens") {
        stop("homo_sapiens is not allowed, use 'human' or others")
      }
      self$Mode <- stringr::str_to_upper(Mode)
      message(glue::glue(">> Using {self$Mode} pipeline ..."))
      init_log <- c(init_log, glue::glue(">> Using {self$Mode} pipeline ..."))
      self$user_email <- user_email
      message(glue::glue(
        ">> Runing progress will be sent to {self$user_email} ..."
      ))
      init_log <- c(
        init_log,
        glue::glue(">> Runing progress will be sent to {self$user_email} ...")
      )
      self$userspace <- userspace
      self$error <- error
      self$C1 = C1
      self$C2 = C2
      self$T1 = T1
      self$T2 = T2
      self$read1_5 = read1_5
      self$read1_3 = read1_3
      self$read2_5 = read2_5
      self$read2_3 = read2_3
      self$seq_deth = seq_deth
      self$pdata = pdata
      self$uploadfile = uploadfile
      self$cgGR_gz = cgGR_gz
      self$CGI = CGI
      if (length(gnome_fasta) == 1) {
        gnome_fasta <- c(gnome_fasta, "placeholder")
      }
      self$gnome_fasta = gnome_fasta
      if (length(genomeFile) == 1) {
        genomeFile <- c(genomeFile, "placeholder")
      }
      self$genomeFile = genomeFile
      if (length(rnaseq_gtf) == 1) {
        rnaseq_gtf <- c(rnaseq_gtf, "placeholder")
      }
      self$rnaseq_gtf = rnaseq_gtf
      if (length(rnaseq_ref) == 1) {
        rnaseq_ref <- c(rnaseq_ref, "placeholder")
      }
      self$rnaseq_ref = rnaseq_ref
      if (length(genomeAnno) == 1) {
        genomeAnno <- c(genomeAnno, "placeholder")
      }
      self$genomeAnno = genomeAnno

      # 一些需要计算的参数
      if (is.null(species)) {
        self$species <- c(species1, species2)
      } else {
        self$species <- species
      }

      self$species1 <- species1
      self$species2 <- species2

      if (length(c(species1, species2)) < 2) {
        self$fixed = ""
      } else {
        self$fixed = "fixed_"
      }

      self$graft <- graft
      # Add rule for graft calculation when species length is 1
      if (length(c(species1, species2)) < 2) {
        self$graft <- species1
      }
      if (graft == species1) {
        self$host = species2
      } else {
        self$host = species1
      }

      if (!is.null(species1) & !is.null(species2)) {
        self$PDX_pipeline = T
      } else {
        self$PDX_pipeline = F
      }
      message(glue::glue(">> PDX mode is set to {self$PDX_pipeline} ..."))
      init_log <- c(
        init_log,
        glue::glue(">> PDX mode is set to {self$PDX_pipeline} ...")
      )
      self$suffix1 = suffix1
      if (is.null(suffix2)) {
        suffix2 = gsub(1, 2, suffix1)
        if (suffix2 == suffix1) {
          suffix2 = gsub(2, 1, suffix1)
        }
        self$suffix2 = suffix2
      } else {
        self$suffix2 = suffix2
      }
      message(glue::glue(
        ">> Suffixs of raw fastq files are {self$suffix1} and {self$suffix2}."
      ))
      init_log <- c(
        init_log,
        glue::glue(
          ">> Suffixs of raw fastq files are {self$suffix1} and {self$suffix2}."
        )
      )
      if (is.null(chrs)) {
        if (graft == "human") {
          self$chrs <- paste0("chr", c(1:22))
        } else {
          self$chrs <- c(1:18) %>% as.character()
        }
      } else {
        self$chrs <- chrs
      }
      # userid in the userspace
      message(">> Create task workflows ...")
      init_log <- c(init_log, ">> Create task workflows ...")

      gen_userid <- function(bytes = 20, task_dir) {
        random_userid <- openssl::rand_bytes(bytes) %>% paste0(., collapse = "")
        exsit_task <- list.dirs(path = task_dir, full.names = F)
        while (random_userid %in% exsit_task) {
          random_userid <- openssl::rand_bytes(bytes) %>%
            paste0(., collapse = "")
        }
        return(random_userid)
      }
      if (is.null(userid)) {
        self$userid <- gen_userid(bytes = 20, task_dir = userspace)
      } else if (
        userid %in%
          list.dirs(path = userspace, full.names = F) &
          new_userid_always
      ) {
        self$userid <- gen_userid(bytes = 20, task_dir = userspace)
      } else {
        self$userid <- userid
      }

      message(glue::glue(">> Create Jobid:{self$userid}"))
      init_log <- c(init_log, glue::glue(">> Create Jobid:{self$userid}"))

      # folders
      masterDir = paste0(userspace, "/", self$userid)
      self$fastqDir = paste0(masterDir, fastqDir)
      self$workflowDir = paste0(masterDir, workflowDir)
      self$analysisDir = paste0(masterDir, analysisDir)
      self$selfconfig = paste0(masterDir, selfconfig)
      self$yaml_file = paste0(masterDir, selfconfig, "/config.yaml")
      self$qcDir = paste0(masterDir, workflowDir, qcDir)
      self$qcDir_before = paste0(masterDir, workflowDir, qcDir_before)
      self$qcDir_after = paste0(masterDir, workflowDir, qcDir_after)
      self$methrixh5 = paste0(masterDir, workflowDir, outDir_mCall, methrixh5)
      self$GCbias = paste0(masterDir, workflowDir, qcDir, GCbias)
      self$SID_log = paste0(masterDir, workflowDir, SID_log)
      self$trimDir = paste0(masterDir, workflowDir, trimDir)
      self$bsmapDir = paste0(masterDir, workflowDir, bsmapDir)
      self$bsmapDir_bamtmp = paste0(masterDir, workflowDir, bsmapDir_bamtmp)
      self$outDir_mCall = paste0(masterDir, workflowDir, outDir_mCall)
      self$ourDirUmx = paste0(masterDir, workflowDir, ourDirUmx)
      self$outdir_qualimap = paste0(masterDir, workflowDir, outdir_qualimap)
      self$outDir_mhap = paste0(masterDir, workflowDir, outDir_mhap)
      self$RData_folder = paste0(masterDir, workflowDir, RData_folder)
      self$clubcpg = paste0(masterDir, workflowDir, clubcpg)
      self$clubcpg_coverage_before = paste0(
        masterDir,
        workflowDir,
        clubcpg_coverage_before
      )
      self$clubcpg_model = paste0(masterDir, workflowDir, clubcpg_model)
      self$clubcpg_coverage_impute = paste0(
        masterDir,
        workflowDir,
        clubcpg_coverage_impute
      )
      self$qc_summary = paste0(masterDir, qc_summary)
      self$logsummary = paste0(masterDir, logsummary)
      self$outDir_betaM = paste0(masterDir, analysisDir, outDir_betaM)
      self$uxm_summary = paste0(masterDir, analysisDir, uxm_summary)
      self$DMR_folder = paste0(masterDir, analysisDir, DMR_folder)
      # end_point
      if (workflow_endpoint == "1") {
        temp_endpoint <- c(T, F, F)
        names(temp_endpoint) <- paste0("step", c(1:length(temp_endpoint)))
      } else if (workflow_endpoint == "2") {
        temp_endpoint <- c(T, T, F)
        names(temp_endpoint) <- paste0("step", c(1:length(temp_endpoint)))
      } else {
        temp_endpoint <- c(T, T, T)
        names(temp_endpoint) <- paste0("step", c(1:length(temp_endpoint)))
      }
      self$workflow_endpoint <- temp_endpoint
      message(glue::glue(
        ">> The beaverflow will be ended in step {workflow_endpoint}"
      ))
      init_log <- c(
        init_log,
        glue::glue(
          ">> The beaverflow will be ended in step {workflow_endpoint}"
        )
      )
      # samples adapters pdata_filter uploadfiles
      message(">> Check Fastq files ...")

      samples <- uploadfile$name %>%
        stringr::str_remove(., self$suffix1) %>%
        stringr::str_remove(., self$suffix2)

      message(glue::glue(
        ">> Found {length(samples)} samples: {paste(samples,collapse = ',')}"
      ))
      init_log <- c(
        init_log,
        glue::glue(
          ">> Found {length(samples)} samples: {paste(samples,collapse = ',')}"
        )
      )
      samples_paired <- samples %>%
        {
          temp <- .
          temp_table <- table(temp)
          temp_table <- temp_table[temp_table == 2]
          names(temp_table)
        }
      message(glue::glue(
        ">> Found {length(samples_paired )} paired_samples: {paste(samples_paired ,collapse = ',')}"
      ))
      init_log <- c(
        init_log,
        glue::glue(
          ">> Found {length(samples_paired )} paired_samples: {paste(samples_paired ,collapse = ',')}"
        )
      )
      if (length(samples_paired) == 0) {
        message(glue::glue(
          ">> Please check your input suffix1: {self$suffix1} "
        ))
        init_log <- c(
          init_log,
          glue::glue(">> Please check your input suffix1: {self$suffix1} ")
        )
      }
      self$samples <- samples_paired
      self$uploadfile <- uploadfile %>%
        dplyr::mutate(sampleid = samples) %>%
        dplyr::filter(sampleid %in% samples_paired)
      message(">> Check Phenodata ...")
      # check pdata data.frame and its cols
      if (ncol(pdata) == 0 | !("sampleid" %in% colnames(pdata))) {
        pdata <- data.frame(
          sampleid = samples_paired
        ) %>%
          dplyr::mutate(inline_barcode_sequence = NA, sample_group = NA)
      } else {
        if (!("inline_barcode_sequence" %in% colnames(pdata))) {
          pdata <- pdata %>%
            dplyr::mutate(inline_barcode_sequence = NA)
        }
        if (!("sample_group" %in% colnames(pdata))) {
          pdata <- pdata %>%
            dplyr::mutate(sample_group = NA)
        }
      }

      pdata_filter <- pdata %>%
        dplyr::filter(sampleid %in% samples_paired)

      self$pdata <- pdata_filter
      # group levels calculation
      sample_group_levels <- levels(factor(pdata_filter[["sample_group"]])) %>%
        length()

      if (sample_group_levels == 0) {
        message(">> sample_group information is not available")
      } else if (sample_group_levels == 1) {
        message(">> 1 group level is found")
      } else {
        message(glue::glue(
          ">> {sample_group_levels} group levels are detected,including: {paste(levels(factor(pdata_filter[['sample_group']])),collapse =',')} "
        ))
      }

      self$group_levels <- sample_group_levels

      # adapter calculation
      trimSeq1 = rep(adapter1, length(samples_paired))
      trimSeq2 = rep(adapter2, length(samples_paired))
      for (i in 1:length(samples_paired)) {
        inline_barcode_revComp = pdata_filter %>%
          dplyr::filter(sampleid %in% samples_paired[i]) %>%
          {
            temp <- .
            string <- revCompString(temp[["inline_barcode_sequence"]][1])
            string
          }

        if (inline_barcode_revComp == "") {
          trimSeq1[i] = "NO_ADAPTER_CAL_USE_DEFAULT"
          trimSeq2[i] = "NO_ADAPTER_CAL_USE_DEFAULT"
        } else if (stringr::str_to_upper(Mode) == "RRBS") {
          trimSeq1[i] = paste0("TGA", inline_barcode_revComp, trimSeq1[i])
          trimSeq2[i] = paste0("A", inline_barcode_revComp, trimSeq2[i])
        } else {
          trimSeq1[i] = paste0(inline_barcode_revComp, trimSeq1[i])
          trimSeq2[i] = paste0(inline_barcode_revComp, trimSeq2[i])
        }
      }
      message(">> Calculate Adapters ...")
      if (length(trimSeq1) == 1) {
        trimSeq1 <- c(trimSeq1, "placeholder")
        trimSeq2 <- c(trimSeq2, "placeholder")
      }
      self$adapter1 <- trimSeq1
      self$adapter2 <- trimSeq2
      message(">> Done!")
      self$gandalf_info()
      # complete init log for front-end display
      self$init_log <- c(
        init_log,
        ">> Check Phenodata ...",
        ">> Calculate Adapters ...",
        ">> Done!",
        ">>> BeaverGandalf:Hey,my dear friends!I will lead you throught the cold night of Middle-earth."
      )
    },
    # 创建BeaverGandalf时的欢迎词
    #' @usage \method{gandalf_info}{BeaverGandalf}()
    #'
    #' @return \code{NULL} (prints a message to the console).
    #' @export
    gandalf_info = function() {
      message(glue::glue(
        ">>> I am BeaverGandalf.Today is {Sys.time()}. My dear friends!I will lead you throught the cold night of Middle-earth. "
      ))
    },

    # 从temp文件夹move文件到运行目录下
    #' @param method \code{character} The method to use for file transfer. Options are:
    #'   \itemize{
    #'     \item \code{"copy"}: Copy the files to the workflow directory.
    #'     \item \code{"move"}: Move the files to the workflow directory (default).
    #'   }
    #'
    #' @return A data frame containing the original file paths and the new paths in the workflow directory.
    #'
    #' @details
    #' - The method checks if the target directory exists and creates it if necessary.
    #' - If a file already exists in the target directory, it will not be copied or moved again.
    #' - The method logs each file transfer operation and updates the `run_log` field.
    #'
    gandalf_fastq_move = function(method = c("copy", "move")) {
      file_df <- self$uploadfile %>%
        dplyr::mutate(newfile_path = paste0(self$fastqDir, "/", name))
      fs::dir_create(self$fastqDir)
      for (i in 1:nrow(file_df)) {
        message(glue::glue(">> processing {i}/{nrow(file_df)}"))
        self$run_log <- c(
          self$run_log,
          glue::glue(">> processing {i}/{nrow(file_df)}")
        )
        if (method == "move") {
          if (!file.exists(file_df$newfile_path[i])) {
            fs::file_move(
              path = file_df$filepath[i],
              new_path = file_df$newfile_path[i]
            )
          }
        } else if (method == "copy") {
          if (!file.exists(file_df$newfile_path[i])) {
            fs::file_copy(
              path = file_df$filepath[i],
              new_path = file_df$newfile_path[i]
            )
          }
        } else {
          self$run_log <- c(
            self$run_log,
            "the method should be one of copy or move"
          )
          stop("the method should be one of copy or move")
        }
      }
      return(file_df)
    },

    # 创建运行时需要的所有文件目录
    #' Create Required Directories for the Workflow
    #'
    #' This method creates all necessary directories for the bioinformatics workflow.
    #' It ensures that the directories for data storage, analysis results, quality control,
    #' and other intermediate files are available before running the pipeline.
    #'
    #' @usage \method{gandalf_create_filework}{BeaverGandalf}()
    #'
    #' @return A character vector containing the paths of all created directories.
    #'
    #' @details
    #' - The method creates directories for various components of the workflow, including:
    #'   - User space and FASTQ files
    #'   - Workflow, analysis, and QC directories
    #'   - Directories for specific tools (e.g., BSMAP, Qualimap, Methrix)
    #'   - Directories for intermediate and final results (e.g., CpG coverage, DMR results)
    #' - If a directory already exists, it will not be recreated.
    #' - The method logs each directory creation operation and updates the `run_log` field.
    #'
    gandalf_create_filework = function() {
      fileworks <- c(
        self$userspace,
        self$fastqDir,
        self$workflowDir,
        self$analysisDir,
        self$selfconfig,
        self$qcDir,
        self$qcDir_before,
        self$qcDir_after,
        self$methrixh5,
        self$GCbias,
        self$SID_log,
        self$trimDir,
        self$bsmapDir,
        self$bsmapDir_bamtmp,
        self$outDir_mCall,
        self$ourDirUmx,
        self$outdir_qualimap,
        self$outDir_mhap,
        self$RData_folder,
        self$clubcpg,
        self$clubcpg_coverage_before,
        self$clubcpg_model,
        self$clubcpg_coverage_impute,
        self$qc_summary,
        self$logsummary,
        self$outDir_betaM,
        self$uxm_summary,
        self$DMR_folder,
        paste0(self$bsmapDir_bamtmp, "/", self$species1),
        paste0(self$bsmapDir_bamtmp, "/", self$species2),
        paste0(self$bsmapDir, "/", self$species1),
        paste0(self$bsmapDir, "/", self$species2),
        paste0(self$bsmapDir, "/Filtered_bams")
      ) %>%
        unique()

      message(glue::glue(">> Create {length(fileworks)} dirs."))
      self$run_log <- c(
        self$run_log,
        glue::glue(">> Create {length(fileworks)} dirs.")
      )
      for (i in 1:length(fileworks)) {
        fs::dir_create(fileworks[i])
      }
      return(fileworks)
    },
    # 创建snakemake运行需要的config文件
    # 放在任务目录里面
    #' Generate YAML Configuration File for the Workflow
    #'
    #' This method creates a YAML configuration file containing all necessary parameters
    #' and directory paths for the bioinformatics workflow. The generated YAML file is
    #' used by Snakemake or other workflow management tools to execute the pipeline.
    #'
    #' @usage \method{gandalf_make_config}{BeaverGandalf}()
    #' @param returnData retrun the config list when True,default as False
    #' @param writePdata write pdata into config folder as .excel,default as True
    #'
    #' @return A named list containing the configuration parameters written to the YAML file.
    #'
    #' @details
    #' - The method collects all relevant parameters from the BeaverGandalf object,
    #'   including pipeline mode, species, adapter sequences, directory paths, and more.
    #' - It writes these parameters to a YAML file specified by `self$yaml_file`.
    #' - The method ensures that the configuration directory (`self$selfconfig`) exists
    #'   before writing the file.
    #' - The generated YAML file includes paths to genome files, reference data, and
    #'   directories for analysis results, QC, and intermediate files.
    #'

    gandalf_make_config = function(returnData = FALSE, writePdata = TRUE) {
      yaml_config_list <- list(
        Mode = self$Mode,
        userid = self$userid,
        jobid = self$userid,
        species = self$species,
        graft = self$graft,
        host = self$host,
        suffix = self$suffix1,
        suffix2 = self$suffix2,
        error = self$error,
        trimSeq1 = self$adapter1,
        trimSeq2 = self$adapter2,
        C1 = self$C1,
        C2 = self$C2,
        T1 = self$T1,
        T2 = self$T2,
        genomeFile = self$genomeFile,
        gnome_fasta = self$gnome_fasta,
        genomeAnno = self$genomeAnno,
        #hg19_genomeFile = self$hg19_genomeFile,
        #cgGR = self$cgGR,
        cgGR_gz = self$cgGR_gz,
        CGI = self$CGI,
        #CGIRData = self$CGIRData,
        #CCGG = self$CCGG,
        #CpG  = self$CpG,
        workDir = paste0(self$userspace, "/", self$userid),
        workflowDir = self$workflowDir,
        analysisDir = self$analysisDir,
        selfconfig = self$selfconfig,
        qcDir = self$qcDir,
        qcDir_before = self$qcDir_before,
        qcDir_after = self$qcDir_after,
        SID_log = self$SID_log,
        trimDir = self$trimDir,
        bsmapDir = self$bsmapDir,
        bsmapDir_bamtmp = self$bsmapDir_bamtmp,
        outDir_mCall = self$outDir_mCall,
        ourDirUmx = self$ourDirUmx,
        outdir_qualimap = self$outdir_qualimap,
        outDir_mhap = self$outDir_mhap,
        RData_folder = self$RData_folder,
        DMR_folder = self$DMR_folder,
        rawDir = self$fastqDir,
        outDir_betaM = self$outDir_betaM,
        qc_summary = self$qc_summary,
        logsummary = self$logsummary,
        uxm_summary = self$uxm_summary,
        SIDs = self$samples,
        read1_5 = self$read1_5,
        read1_3 = self$read1_3,
        read2_5 = self$read2_5,
        read2_3 = self$read2_3,
        seq_deth = self$seq_deth,
        fixed = self$fixed,
        clubcpg = self$clubcpg,
        clubcpg_coverage_before = self$clubcpg_coverage_before,
        clubcpg_model = self$clubcpg_model,
        clubcpg_coverage_impute = self$clubcpg_coverage_impute,
        chrs = self$chrs,
        rnaseq_gtf = self$rnaseq_gtf,
        rnaseq_ref = self$rnaseq_ref,
        methrixh5 = self$methrixh5,
        GCbias = self$GCbias,
        user_email = self$user_email,
        PDX_pipeline = self$PDX_pipeline,
        group_levels = self$group_levels
      )
      message(">> writing config files ...")
      self$run_log <- c(self$run_log, ">> writing config files ...")
      fs::dir_create(self$selfconfig)
      yaml::write_yaml(yaml_config_list, file = self$yaml_file)
      if (writePdata) {
        message(">> writing pdata tables ...")
        self$run_log <- c(self$run_log, ">> writing pdata tables ...")
        openxlsx::write.xlsx(self$pdata, paste0(self$selfconfig, "/pdata.xlsx"))
      }
      if (returnData) {
        return(yaml_config_list)
      }
    },

    # 任务流程函数，实际运行的任务
    #' Launch and Manage the Bioinformatics Workflow
    #'
    #' This method initiates and manages the execution of the bioinformatics workflow
    #' using Snakemake. It supports multiple execution environments, including Kubernetes,
    #' Slurm, and containerized environments. The method configures the workflow based
    #' on the provided parameters and runs the pipeline in the specified mode.
    #'
    #' @param jobflow \code{character} The directory containing the Snakemake workflow files (default: "workflows").
    #' @param enigent \code{character} The execution environment detected by \code{beaver_engine_detect()} (default: result of \code{beaver_engine_detect()}).
    #' @param snakemake_condaenv \code{character} The name of the Conda environment to use for Snakemake (default: "").
    #' @param dry_run \code{logical} Whether to perform a dry run without executing the workflow (default: FALSE).
    #' @param partition \code{character} The partition of resources used by Slurm cluster, only works in Slurm mode (default: "amd_512").
    #' @param cpus \code{character vector} The CPU cores used in the 3 steps (default: c("20", "40", "10")).
    #' @param mem \code{character vector} The memory used in the 3 steps (default: c("100G", "400G", "400G")).
    #' @param dwarf_workers \code{numeric} The parallel number for container/k8s mode using future package (default: 1). Only used in container and k8s environments.
    #' @param max_retries \code{numeric} Maximum number of retry attempts for failed Slurm jobs (default: 3). Only used in Slurm mode.
    #' @param array_concurrent \code{numeric} Maximum number of concurrent Job Array tasks in Slurm mode (default: 10). Will be automatically adjusted if greater than sample count. Only used in Slurm mode.
    #'
    #' @return \code{NULL} (executes the workflow and logs the process).
    #'
    #' @details
    #' The method detects the execution environment using \code{beaver_engine_detect()} and runs accordingly:
    #' \itemize{
    #'   \item \strong{Kubernetes (k8s)}: Uses kubectl to submit jobs
    #'   \item \strong{Container}: Uses future/furrr for parallel processing with \code{dwarf_workers}
    #'   \item \strong{Slurm}: Uses sbatch with Job Arrays for parallel sample processing.
    #'     Step 1 runs as a single job, Step 2/3 use Job Arrays with automatic retry on failure.
    #'     Jobs are chained using \code{--dependency=afterok} to ensure proper execution order.
    #' }
    #'
    #' For Slurm mode:
    #' \itemize{
    #'   \item Each sample in Step 2/3 is processed as an independent array task
    #'   \item Failed tasks are automatically retried up to \code{max_retries} times
    #'   \item Success is tracked via marker files in the log directory
    #'   \item Job status can be monitored via \code{self$slurm_jobs} data frame
    #' }
    #'

    gandalf2wars = function(
      jobflow = "workflows",
      enigent = beaver_engine_detect(),
      snakemake_condaenv = "",
      dry_run = FALSE,
      partition = "amd_512",
      cpus = c("20", "40", "10"),
      mem = c("100G", "400G", "400G"),
      dwarf_workers = 1,
      max_retries = 3,
      array_concurrent = 10
    ) {
      require("future")
      message(">> Configuring cpu paramters.")
      if (length(cpus) > 3) {
        message(">> Too much steps,use the first 3 steps.")
        cpus <- cpus[1:3]
      } else if (length(cpus) == 1) {
        message(">> Complimentation of cpu usage plan with default setting.")
        cpus <- c(cpus, "40", "10")
      } else if (length(cpus) == 2) {
        message(">> Complimentation of cpu usage plan with default setting.")
        cpus <- c(cpus, "10")
      } else {
        message(">> Plan for cpu usage created.")
      }
      message(">> Configuring mem paramters.")
      if (length(mem) > 3) {
        message(">> Too much steps,use the first 3 steps.")
        mem <- mem[1:3]
      } else if (length(mem) == 1) {
        message(">> Complimentation of mem usage plan with default setting.")
        mem <- c(mem, "400G", "400G")
      } else if (length(mem) == 2) {
        message(">> Complimentation of mem usage plan with default setting.")
        mem <- c(mem, "400G")
      } else {
        message(">> Plan for mem usage created.")
      }

      # processing dwarf workers used in future package Parallel processing

      max_dwarf_workfers <- parallel::detectCores()
      if (dwarf_workers < 1 | !is.numeric(dwarf_workers)) {
        dwarf_workers <- 1
      }

      if (dwarf_workers <= max_dwarf_workfers & dwarf_workers > 1) {
        message(glue::glue(
          ">> {dwarf_workers} dwarf_workers are in call.Parallel processing is enable."
        ))
      } else if (dwarf_workers == 1) {
        message(">> 1 dwarf_worker is in call.Sequential processing is used.")
      } else {
        message(glue::glue(
          ">> Too many dwarf_workers are request. Only {max_dwarf_workfers} dwarf_workers are in call.Parallel processing is enable."
        ))
        dwarf_workers <- max_dwarf_workfers
      }

      if (self$PDX_pipeline) {
        if (self$Mode == "RNASEQ") {
          workflow_idx = glue::glue("Beaver{self$Mode}PDX")
          job_idx = "rnaseq"
        } else {
          workflow_idx = glue::glue("BeaverPDX")
          job_idx = "bsseq"
        }
      } else if (self$Mode == "RNASEQ") {
        workflow_idx = "BeaverRNA"
        job_idx = "rnaseq"
      } else {
        workflow_idx = "BeaverBS"
        job_idx = "bsseq"
      }

      snakemake_condaenv_bk <- snakemake_condaenv
      if (snakemake_condaenv != "") {
        snakemake_condaenv <- paste("conda run -n ", snakemake_condaenv)
      }
      if (enigent %in% "k8s") {
        mem = paste0(mem, "i")
      }

      if (dry_run) {
        dryrun <- "-n"
      } else {
        dryrun <- ""
      }

      task_df = data.frame(
        steps = paste0("step", c(1:3)),
        cpus = cpus,
        mem = mem,
        endpoint = self$workflow_endpoint
      ) %>%
        dplyr::filter(endpoint == T)
      if (self$Mode == "RNASEQ" & nrow(task_df) == 3 & !(self$PDX_pipeline)) {
        task_df <- task_df[1:2, ]
      }
      message(glue::glue(
        ">> This workflow will be ended in step {nrow(task_df)}"
      ))

      self$run_log <- c(
        self$run_log,
        glue::glue(">> This workflow will be ended in step {nrow(task_df)}")
      )

      if (enigent %in% "k8s") {
        message(glue::glue(">> configure job files ... "))

        # read & write job yaml files
        # in future : implement of ClusterFunctions for Docker from batchtools package in https://mllg.github.io/batchtools/reference/makeClusterFunctionsDocker

        for (i in 1:nrow(task_df)) {
          if (task_df$steps[i] == "step1") {
            message(">> [", Sys.time(), "] Run in Step 1")
            self$run_log <- c(
              self$run_log,
              glue::glue(">> [{Sys.time()}] Run in Step 1")
            )
            command <- glue::glue(
              "cd /home/builduser/beaverflow && {snakemake_condaenv} snakemake {dryrun} --cores all --snakefile {workflow_idx}_step{i}.snakemake --configfile {self$yaml_file} --rerun-incomplete"
            )
            job_yaml <- yaml::read_yaml(
              file = glue::glue("workflows/{job_idx}_step{i}.yaml")
            )
            job_yaml$spec$template$spec$containers[[1]]$command[3] <- command
            new_job_config <- paste0(
              self$selfconfig,
              "/job_",
              task_df$steps[i],
              ".yaml"
            )
            yaml::write_yaml(job_yaml, new_job_config)
            time_usage <- system.time({
              status <- system(
                command = glue::glue("kubectl apply -f {new_job_config}"),
                intern = T
              )
            })

            self$run_log <- c(
              self$run_log,
              status,
              glue::glue(
                ">> Done! Elapsed time:{round(time_usage['elapsed'],digits = 3)}s"
              )
            )
            message(
              ">> Done! Elapsed time : ",
              round(time_usage["elapsed"], digits = 3),
              "s"
            )
          } else {
            message(">> Run by per-sample in Step 2 and Step 3")
            self$run_log <- c(
              self$run_log,
              ">> Run by per-sample in Step 2 and Step 3"
            )
            configfiles <- yaml::read_yaml(self$yaml_file)
            # in future: use future framework to doParallel
            for (a in 1:length(self$samples)) {
              message(glue::glue(
                ">> [{Sys.time()}]Processing sample {a}/{length(self$samples)} in step {i}"
              ))
              self$run_log <- c(
                self$run_log,
                glue::glue(
                  ">> [{Sys.time()}]Processing sample {a}/{length(self$samples)} in step {i}"
                )
              )
              configfiles$SIDs <- self$samples[a]
              new_yaml_config <- paste0(
                self$selfconfig,
                "/",
                self$samples[a],
                ".yaml"
              )
              yaml::write_yaml(configfiles, new_yaml_config)
              command <- glue::glue(
                "cd /home/builduser/beaverflow && {snakemake_condaenv} snakemake {dryrun} --cores all --snakefile {workflow_idx}_step{i}.snakemake --configfile {new_yaml_config} --rerun-incomplete"
              )
              job_yaml <- yaml::read_yaml(
                file = glue::glue("workflows/{job_idx}_step{i}.yaml")
              )
              job_yaml$spec$template$spec$containers[[1]]$command[3] <- command
              new_job_config <- paste0(
                self$selfconfig,
                "/job_",
                task_df$steps[i],
                "_",
                self$samples[a],
                ".yaml"
              )
              yaml::write_yaml(job_yaml, new_job_config)
              time_usage <- system.time({
                status <- system(
                  command = glue::glue("kubectl apply -f {new_job_config}"),
                  intern = T
                )
              })

              self$run_log <- c(
                self$run_log,
                status,
                glue::glue(
                  ">> Done! Elapsed time:{round(time_usage['elapsed'],digits = 3)}s"
                )
              )
              message(
                ">> Done! Elapsed time : ",
                round(time_usage["elapsed"], digits = 3),
                "s"
              )
            }

            message(glue::glue(
              ">> [{Sys.time()}]Aggather the Results from Step {i}"
            ))
            self$run_log <- c(
              self$run_log,
              glue::glue(">> [{Sys.time()}]Aggather the Results from Step {i}")
            )
            command <- glue::glue(
              "cd /home/builduser/beaverflow && {snakemake_condaenv} snakemake {dryrun}  --cores all --snakefile {workflow_idx}_step{i}_checker.snakemake --configfile {self$yaml_file} --rerun-incomplete"
            )
            job_yaml <- yaml::read_yaml(
              file = glue::glue("workflows/{job_idx}_step{i}.yaml")
            )
            job_yaml$spec$template$spec$containers[[1]]$command[3] <- command
            new_job_config <- paste0(
              self$selfconfig,
              "/job_",
              task_df$steps[i],
              ".yaml"
            )
            yaml::write_yaml(job_yaml, new_job_config)
            time_usage <- system.time({
              status <- system(
                command = glue::glue("kubectl apply -f {new_job_config}"),
                intern = T
              )
            })

            self$run_log <- c(
              self$run_log,
              status,
              glue::glue(
                ">> Done! Elapsed time:{round(time_usage['elapsed'],digits = 3)}s"
              )
            )
            message(
              ">> Done! Elapsed time : ",
              round(time_usage["elapsed"], digits = 3),
              "s"
            )
          }
        }
      } else if (enigent %in% "container") {
        message(">> Run in container Mode")
        for (i in 1:nrow(task_df)) {
          if (task_df$steps[i] == "step1") {
            message(glue::glue(">> [{Sys.time()}] Run in Step 1"))
            self$run_log <- c(
              self$run_log,
              glue::glue(">> [{Sys.time()}] Run in Step 1")
            )
            command <- glue::glue(
              "{snakemake_condaenv} snakemake {dryrun} --cores all --snakefile {workflow_idx}_step{i}.snakemake --configfile {self$yaml_file} --rerun-incomplete"
            )

            time_usage <- system.time({
              status <- system(command = command, intern = T)
            })

            self$run_log <- c(
              self$run_log,
              status,
              glue::glue(
                ">> Done! Elapsed time:{round(time_usage['elapsed'],digits = 3)}s"
              )
            )
            message(
              ">> Done! Elapsed time : ",
              round(time_usage["elapsed"], digits = 3),
              "s"
            )
          } else {
            message(">> Run by per-sample in Step 2 and Step 3")
            self$run_log <- c(
              self$run_log,
              ">> Run by per-sample in Step 2 and Step 3"
            )
            configfiles <- yaml::read_yaml(self$yaml_file)

            # use future Parallel framework
            future::plan(future::multisession, workers = dwarf_workers)
            progressr::handlers(global = TRUE)
            progressr::handlers(
              progressr::handler_progress(
                format = ":eta [:bar] :percent | :message",
                clear = FALSE,
                show_after = 0
              )
            )
            progressr::with_progress({
              # 初始化进度条（总数等于任务数）
              p <- progressr::progressor(steps = length(self$samples) * 2)
              dwarf_results <- furrr::future_map(
                1:length(self$samples),
                function(a) {
                  init_dwarf_work <- glue::glue(
                    ">>  [{Sys.time()}]Processing sample {a}/{length(self$samples)} in step {i}"
                  )
                  p(message = init_dwarf_work)
                  configfiles$SIDs <- self$samples[a]
                  new_yaml_config <- paste0(
                    self$selfconfig,
                    "/",
                    self$samples[a],
                    ".yaml"
                  )
                  yaml::write_yaml(configfiles, new_yaml_config)
                  command <- glue::glue(
                    "{snakemake_condaenv} snakemake {dryrun} --cores all --snakefile {workflow_idx}_step{i}.snakemake --configfile {new_yaml_config} --rerun-incomplete"
                  )
                  message(command)
                  time_usage <- system.time({
                    status <- system(command = command, intern = T)
                  })

                  #message(status)
                  # 生成完成消息并追加到进度条
                  finish_msg <- glue::glue(
                    ">> Sample {a} done | ",
                    "Time: {round(time_usage['elapsed'], 3)}s | ",
                    "Status: {status}" # 简化状态输出
                  )
                  p(message = finish_msg) # 再次更新进度条（可选，根据需求调整频次）
                  list(
                    summary_report = c(
                      init_dwarf_work,
                      status,
                      glue::glue(
                        ">> Done! Elapsed time:{round(time_usage['elapsed'],digits = 3)}s"
                      )
                    )
                  )
                }
              )
            })
            # merge logs
            self$run_log <- c(self$run_log, unlist(dwarf_results))
            # release workers

            future::plan(future::sequential)

            message(glue::glue(
              ">>  [{Sys.time()}]Aggather the Results from Step {i}"
            ))
            self$run_log <- c(
              self$run_log,
              glue::glue(">>  [{Sys.time()}]Aggather the Results from Step {i}")
            )
            command <- glue::glue(
              "{snakemake_condaenv} snakemake  {dryrun} --cores all --snakefile {workflow_idx}_step{i}_checker.snakemake --configfile {self$yaml_file} --rerun-incomplete"
            )
            time_usage <- system.time({
              status <- system(command = command, intern = T)
            })

            self$run_log <- c(
              self$run_log,
              status,
              glue::glue(
                ">> Done! Elapsed time:{round(time_usage['elapsed'],digits = 3)}s"
              )
            )
            message(
              ">> Done! Elapsed time : ",
              round(time_usage["elapsed"], digits = 3),
              "s"
            )
          }
        }
      } else {
        # Slurm mode - Use Job Array with dependency management and auto-retry
        message(">> Run in Slurm cluster Mode with Job Array")
        self$run_log <- c(
          self$run_log,
          ">> Run in Slurm cluster Mode with Job Array"
        )

        # Prepare sample configs for Job Array
        configfiles <- yaml::read_yaml(self$yaml_file)
        private$.prepare_sample_configs(configfiles)

        # Adjust array_concurrent to not exceed sample count
        n_samples <- length(self$samples)
        effective_concurrent <- min(array_concurrent, n_samples)
        if (effective_concurrent < array_concurrent) {
          message(glue::glue(
            ">> Adjusted array_concurrent from {array_concurrent} to {effective_concurrent} (sample count)"
          ))
        }

        prev_job_id <- NULL

        for (i in 1:nrow(task_df)) {
          step_num <- as.integer(gsub("step", "", task_df$steps[i]))

          if (step_num == 1) {
            # Step 1: Single job for QC of all samples
            message(glue::glue(">> [{Sys.time()}] Submitting Step 1"))
            self$run_log <- c(
              self$run_log,
              glue::glue(">> [{Sys.time()}] Submitting Step 1")
            )

            script_path <- private$.generate_step1_script(
              workflow_idx = workflow_idx,
              snakemake_condaenv = snakemake_condaenv,
              dryrun = dryrun,
              partition = partition,
              cpus = task_df$cpus[i],
              mem = task_df$mem[i],
              dependency = prev_job_id
            )

            prev_job_id <- private$.submit_sbatch_job(script_path)

            # Wait for Step 1 to complete
            status <- private$.wait_for_job(prev_job_id)

            if (status != "COMPLETED") {
              warning(glue::glue(">> Step 1 failed with status: {status}"))
              self$run_log <- c(
                self$run_log,
                glue::glue(">> WARNING: Step 1 failed with status: {status}")
              )
            } else {
              message(">> Step 1 completed successfully")
              self$run_log <- c(
                self$run_log,
                ">> Step 1 completed successfully"
              )
            }
          } else {
            # Step 2/3: Job Array with per-sample processing and retry logic
            prev_job_id <- private$.run_step_with_retry(
              step = step_num,
              workflow_idx = workflow_idx,
              snakemake_condaenv = snakemake_condaenv,
              dryrun = dryrun,
              partition = partition,
              cpus = task_df$cpus[i],
              mem = task_df$mem[i],
              array_concurrent = effective_concurrent,
              dependency = prev_job_id,
              max_retries = max_retries
            )
          }
        }

        message(glue::glue(">> [{Sys.time()}] All workflow steps completed"))
        self$run_log <- c(
          self$run_log,
          glue::glue(">> [{Sys.time()}] All workflow steps completed")
        )
      }
    },
    # gandalf 下载文件和结果
    #' Download or Aggregate Workflow Results
    #'
    #' This method aggregates the results from the workflow execution and prepares
    #' them for download or further analysis. It supports multiple result types and
    #' compression methods.
    #'
    #' @param resultType \code{character} The type of result to aggregate. Options include:
    #'   \itemize{
    #'     \item \code{"trim"}: Trimmed FASTQ files.
    #'     \item \code{"bam"}: BAM files from alignment.
    #'     \item \code{"matrix"}: Methylation matrix files.
    #'     \item \code{"qc"}: Quality control summary files.
    #'   }
    #' @param method \code{character} The compression method to use. Options include:
    #'   \itemize{
    #'     \item \code{"zip"}: Compress results into a ZIP archive.
    #'     \item \code{"gzip"}: Compress results using gzip.
    #'   }
    #'
    #' @return A list containing the aggregated results, including:
    #'   \itemize{
    #'     \item \code{rootpath}: The root directory of the results.
    #'     \item \code{filedf}: A data frame with file names and paths.
    #'     \item \code{compressfile}: The path to the compressed archive file.
    #'   }
    #'
    gandalf_aggResult = function(resultType, method) {
      if (resultType == "trim") {
        path = self$trimDir
      } else if (resultType == "bam") {
        path = self$bsmapDir
      } else if (resultType == "matrix") {
        path = self$outDir_mCall
      } else if (resultType == "qc") {
        path = self$qc_summary
      } else {
        stop(">> The resultType should one of the: trim,bam,matrix,qc")
      }

      file_list <- file_agg(path = path, method = method)
      return(file_list)
    },
    # gandalf 进度探查
    #' Detect the Current Progress of the Workflow
    #'
    #' This method checks the current progress of the Beaverflow pipeline by examining
    #' the log files in the specified log directory. It determines which steps have been
    #' completed and which step is currently running.
    #'
    #' @usage \method{gandalf_process_discovery}{BeaverGandalf}()
    #'
    #' @return An integer indicating the current step number of the workflow.
    #'
    #' @details
    #' - The method scans the log directory (`self$SID_log`) for files with the pattern
    #'   `*_success.txt` to identify completed steps.
    #' - It calculates the number of completed steps and determines the ongoing step.
    #' - For RNAseq mode, the workflow is limited to two steps, and the method returns
    #'   `2` if the second step is ongoing.
    #' - For other modes, the workflow can have up to three steps, and the method returns
    #'   the current step number (1, 2, or 3).
    #' - The method logs the current progress using the `message` function.
    #'

    gandalf_process_discovery = function() {
      log_dir <- self$SID_log
      files <- list.files(path = log_dir, pattern = "*_success.txt")
      complete_steps <- length(files)
      ongoing_steps <- complete_steps + 1

      if (self$Mode == "RNASEQ" & ongoing_steps > 2) {
        message(glue::glue(">> The Beaverflow is currently runing in step 2"))
        return(2)
      } else if (ongoing_steps > 3) {
        message(glue::glue(">> The Beaverflow is currently runing in step 3"))
        return(3)
      } else {
        message(glue::glue(
          ">> The Beaverflow is currently runing in step {ongoing_steps}"
        ))
        return(ongoing_steps)
      }
    }
    # gandalf QC plots
  ),

  private = list(
    # Submit a sbatch job and return the job ID
    # @param script_path Path to the sbatch script file
    # @return Character string of the job ID
    .submit_sbatch_job = function(script_path) {
      result <- system(
        command = glue::glue("sbatch {script_path}"),
        intern = TRUE
      )
      # Parse job ID from "Submitted batch job 12345"
      job_id <- gsub("Submitted batch job ", "", result)
      message(glue::glue(">> Submitted job: {job_id}"))
      self$run_log <- c(self$run_log, glue::glue(">> Submitted job: {job_id}"))

      # Record job in slurm_jobs
      new_job <- data.frame(
        job_id = job_id,
        script = script_path,
        status = "PENDING",
        submit_time = Sys.time(),
        end_time = as.POSIXct(NA),
        stringsAsFactors = FALSE
      )
      if (is.null(self$slurm_jobs)) {
        self$slurm_jobs <- new_job
      } else {
        self$slurm_jobs <- rbind(self$slurm_jobs, new_job)
      }

      return(job_id)
    },

    # Wait for a Slurm job to complete
    # @param job_id The job ID to wait for
    # @param check_interval Seconds between status checks (default: 30)
    # @return Final job status
    .wait_for_job = function(job_id, check_interval = 30) {
      message(glue::glue(">> Waiting for job {job_id} to complete..."))

      while (TRUE) {
        # Check job status using sacct
        status_cmd <- glue::glue(
          "sacct -j {job_id} --format=State --noheader -P | head -1"
        )
        status <- system(command = status_cmd, intern = TRUE)
        status <- trimws(status[1])

        if (
          status %in%
            c("COMPLETED", "FAILED", "CANCELLED", "TIMEOUT", "NODE_FAIL")
        ) {
          message(glue::glue(">> Job {job_id} finished with status: {status}"))

          # Update slurm_jobs record
          if (!is.null(self$slurm_jobs)) {
            idx <- which(self$slurm_jobs$job_id == job_id)
            if (length(idx) > 0) {
              self$slurm_jobs$status[idx] <- status
              self$slurm_jobs$end_time[idx] <- Sys.time()
            }
          }

          return(status)
        }

        Sys.sleep(check_interval)
      }
    },

    # Wait for a Job Array to complete
    # @param job_id The array job ID
    # @param check_interval Seconds between status checks
    # @return List with completed and failed task indices
    .wait_for_array = function(job_id, check_interval = 30) {
      message(glue::glue(">> Waiting for job array {job_id} to complete..."))

      while (TRUE) {
        # Check all array task statuses
        status_cmd <- glue::glue(
          "sacct -j {job_id} --format=JobID,State --noheader -P"
        )
        status_output <- system(command = status_cmd, intern = TRUE)

        # Parse output
        all_done <- TRUE
        for (line in status_output) {
          parts <- strsplit(line, "\\|")[[1]]
          if (length(parts) >= 2) {
            task_status <- trimws(parts[2])
            if (task_status %in% c("PENDING", "RUNNING", "CONFIGURING")) {
              all_done <- FALSE
              break
            }
          }
        }

        if (all_done) {
          message(glue::glue(">> Job array {job_id} completed"))
          break
        }

        Sys.sleep(check_interval)
      }

      # Get final status of all tasks
      status_cmd <- glue::glue(
        "sacct -j {job_id} --format=JobID,State --noheader -P"
      )
      status_output <- system(command = status_cmd, intern = TRUE)

      completed <- c()
      failed <- c()

      for (line in status_output) {
        parts <- strsplit(line, "\\|")[[1]]
        if (length(parts) >= 2) {
          task_id <- parts[1]
          task_status <- trimws(parts[2])

          # Extract array index from task ID (e.g., "12345_1" -> 1)
          if (grepl("_", task_id)) {
            array_idx <- as.integer(gsub(".*_", "", task_id))
            if (!is.na(array_idx)) {
              if (task_status == "COMPLETED") {
                completed <- c(completed, array_idx)
              } else if (
                task_status %in%
                  c("FAILED", "CANCELLED", "TIMEOUT", "NODE_FAIL")
              ) {
                failed <- c(failed, array_idx)
              }
            }
          }
        }
      }

      return(list(completed = unique(completed), failed = unique(failed)))
    },

    # Prepare sample config files for Job Array
    # @param configfiles Base config list
    # @return Path to samples.txt file
    .prepare_sample_configs = function(configfiles) {
      # Write individual config for each sample
      for (sample in self$samples) {
        configfiles$SIDs <- sample
        config_path <- paste0(self$selfconfig, "/", sample, ".yaml")
        yaml::write_yaml(configfiles, config_path)
      }

      # Write samples list file for array job
      samples_file <- paste0(self$selfconfig, "/samples.txt")
      writeLines(self$samples, samples_file)

      return(samples_file)
    },

    # Get list of failed samples by checking success markers
    # @param step The step number
    # @return Character vector of failed sample IDs
    .get_failed_samples = function(step) {
      success_pattern <- paste0("_step", step, "_success.txt")
      success_files <- list.files(
        path = self$SID_log,
        pattern = success_pattern
      )

      # Extract sample names from success files
      completed_samples <- gsub(success_pattern, "", success_files)

      # Find samples that are not completed
      failed_samples <- setdiff(self$samples, completed_samples)

      return(failed_samples)
    },

    # Generate sbatch script for Step 1
    # @param workflow_idx Workflow identifier
    # @param snakemake_condaenv Conda environment command
    # @param dryrun Dry run flag
    # @param partition Slurm partition
    # @param cpus Number of CPUs
    # @param mem Memory allocation
    # @param dependency Previous job ID for dependency (optional)
    # @return Path to generated script
    .generate_step1_script = function(
      workflow_idx,
      snakemake_condaenv,
      dryrun,
      partition,
      cpus,
      mem,
      dependency = NULL
    ) {
      script_path <- paste0(self$selfconfig, "/slurm_step1.sh")

      dep_line <- ""
      if (!is.null(dependency)) {
        dep_line <- glue::glue("#SBATCH --dependency=afterok:{dependency}")
      }

      script_content <- glue::glue(
        '#!/bin/bash
#SBATCH --job-name=beaver_step1_{self$userid}
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
#SBATCH --partition={partition}
#SBATCH --output={self$SID_log}/step1_%j.out
#SBATCH --error={self$SID_log}/step1_%j.err
{dep_line}

echo ">> Starting Step 1 at $(date)"
echo ">> Job ID: $SLURM_JOB_ID"

{snakemake_condaenv} snakemake {dryrun} --cores all \\
  --snakefile {workflow_idx}_step1.snakemake \\
  --configfile {self$yaml_file} \\
  --rerun-incomplete

if [ $? -eq 0 ]; then
  touch {self$SID_log}/step1_success.txt
  echo ">> Step 1 completed successfully at $(date)"
else
  echo ">> Step 1 failed at $(date)"
  exit 1
fi
'
      )

      writeLines(script_content, script_path)
      return(script_path)
    },

    # Generate sbatch script for Step 2/3 Job Array
    # @param step Step number (2 or 3)
    # @param workflow_idx Workflow identifier
    # @param snakemake_condaenv Conda environment command
    # @param dryrun Dry run flag
    # @param partition Slurm partition
    # @param cpus Number of CPUs
    # @param mem Memory allocation
    # @param array_concurrent Maximum concurrent array tasks
    # @param dependency Previous job ID for dependency
    # @param failed_indices Optional: specific array indices to run (for retries)
    # @return Path to generated script
    .generate_array_script = function(
      step,
      workflow_idx,
      snakemake_condaenv,
      dryrun,
      partition,
      cpus,
      mem,
      array_concurrent,
      dependency = NULL,
      failed_indices = NULL
    ) {
      script_path <- paste0(self$selfconfig, "/slurm_step", step, ".sh")

      dep_line <- ""
      if (!is.null(dependency)) {
        dep_line <- glue::glue("#SBATCH --dependency=afterok:{dependency}")
      }

      # Determine array specification
      n_samples <- length(self$samples)
      if (!is.null(failed_indices) && length(failed_indices) > 0) {
        array_spec <- paste(failed_indices, collapse = ",")
      } else {
        array_spec <- glue::glue("1-{n_samples}%{array_concurrent}")
      }

      script_content <- glue::glue(
        '#!/bin/bash
#SBATCH --job-name=beaver_step{step}_{self$userid}
#SBATCH --array={array_spec}
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
#SBATCH --partition={partition}
#SBATCH --output={self$SID_log}/step{step}_%A_%a.out
#SBATCH --error={self$SID_log}/step{step}_%A_%a.err
{dep_line}

# Read sample name from samples list
SAMPLE=$(sed -n "${{SLURM_ARRAY_TASK_ID}}p" {self$selfconfig}/samples.txt)
CONFIG="{self$selfconfig}/${{SAMPLE}}.yaml"

echo ">> Starting Step {step} for sample $SAMPLE at $(date)"
echo ">> Array Job ID: $SLURM_ARRAY_JOB_ID, Task ID: $SLURM_ARRAY_TASK_ID"

{snakemake_condaenv} snakemake {dryrun} --cores all \\
  --snakefile {workflow_idx}_step{step}.snakemake \\
  --configfile $CONFIG \\
  --rerun-incomplete

if [ $? -eq 0 ]; then
  touch {self$SID_log}/${{SAMPLE}}_step{step}_success.txt
  echo ">> Step {step} for sample $SAMPLE completed successfully at $(date)"
else
  echo ">> Step {step} for sample $SAMPLE failed at $(date)"
  exit 1
fi
'
      )

      writeLines(script_content, script_path)
      return(script_path)
    },

    # Generate sbatch script for Checker job
    # @param step Step number (2 or 3)
    # @param workflow_idx Workflow identifier
    # @param snakemake_condaenv Conda environment command
    # @param dryrun Dry run flag
    # @param partition Slurm partition
    # @param cpus Number of CPUs
    # @param mem Memory allocation
    # @param dependency Previous job ID for dependency
    # @return Path to generated script
    .generate_checker_script = function(
      step,
      workflow_idx,
      snakemake_condaenv,
      dryrun,
      partition,
      cpus,
      mem,
      dependency
    ) {
      script_path <- paste0(self$selfconfig, "/slurm_step", step, "_checker.sh")

      script_content <- glue::glue(
        '#!/bin/bash
#SBATCH --job-name=beaver_step{step}_checker_{self$userid}
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
#SBATCH --partition={partition}
#SBATCH --output={self$SID_log}/step{step}_checker_%j.out
#SBATCH --error={self$SID_log}/step{step}_checker_%j.err
#SBATCH --dependency=afterany:{dependency}

echo ">> Starting Step {step} Checker at $(date)"
echo ">> Job ID: $SLURM_JOB_ID"

{snakemake_condaenv} snakemake {dryrun} --cores all \\
  --snakefile {workflow_idx}_step{step}_checker.snakemake \\
  --configfile {self$yaml_file} \\
  --rerun-incomplete

if [ $? -eq 0 ]; then
  touch {self$SID_log}/step{step}_checker_success.txt
  echo ">> Step {step} Checker completed successfully at $(date)"
else
  echo ">> Step {step} Checker failed at $(date)"
  exit 1
fi
'
      )

      writeLines(script_content, script_path)
      return(script_path)
    },

    # Run Step 2 or 3 with Job Array and retry logic
    # @param step Step number
    # @param workflow_idx Workflow identifier
    # @param snakemake_condaenv Conda environment command
    # @param dryrun Dry run flag
    # @param partition Slurm partition
    # @param cpus Number of CPUs
    # @param mem Memory allocation
    # @param array_concurrent Maximum concurrent array tasks
    # @param dependency Previous job ID
    # @param max_retries Maximum retry attempts
    # @return Final job ID (of checker)
    .run_step_with_retry = function(
      step,
      workflow_idx,
      snakemake_condaenv,
      dryrun,
      partition,
      cpus,
      mem,
      array_concurrent,
      dependency,
      max_retries
    ) {
      message(glue::glue(
        ">> [{Sys.time()}] Starting Step {step} with Job Array"
      ))
      self$run_log <- c(
        self$run_log,
        glue::glue(">> [{Sys.time()}] Starting Step {step} with Job Array")
      )

      # Initial submission
      script_path <- private$.generate_array_script(
        step = step,
        workflow_idx = workflow_idx,
        snakemake_condaenv = snakemake_condaenv,
        dryrun = dryrun,
        partition = partition,
        cpus = cpus,
        mem = mem,
        array_concurrent = array_concurrent,
        dependency = dependency
      )

      job_id <- private$.submit_sbatch_job(script_path)

      # Wait for array to complete
      array_result <- private$.wait_for_array(job_id)

      # Retry failed tasks
      retry_count <- 0
      while (length(array_result$failed) > 0 && retry_count < max_retries) {
        retry_count <- retry_count + 1

        failed_samples <- self$samples[array_result$failed]
        message(glue::glue(
          ">> Retry {retry_count}/{max_retries}: {length(failed_samples)} failed samples"
        ))
        self$run_log <- c(
          self$run_log,
          glue::glue(
            ">> Retry {retry_count}/{max_retries}: Retrying samples: {paste(failed_samples, collapse=', ')}"
          )
        )

        # Generate retry script with only failed indices
        retry_script <- private$.generate_array_script(
          step = step,
          workflow_idx = workflow_idx,
          snakemake_condaenv = snakemake_condaenv,
          dryrun = dryrun,
          partition = partition,
          cpus = cpus,
          mem = mem,
          array_concurrent = array_concurrent,
          dependency = NULL, # No dependency for retries
          failed_indices = array_result$failed
        )

        retry_job_id <- private$.submit_sbatch_job(retry_script)
        array_result <- private$.wait_for_array(retry_job_id)
        job_id <- retry_job_id
      }

      # Check final status
      final_failed <- private$.get_failed_samples(step)
      if (length(final_failed) > 0) {
        warning(glue::glue(
          ">> {length(final_failed)} samples failed after {max_retries} retries: {paste(final_failed, collapse=', ')}"
        ))
        self$run_log <- c(
          self$run_log,
          glue::glue(
            ">> WARNING: {length(final_failed)} samples failed: {paste(final_failed, collapse=', ')}"
          )
        )
      } else {
        message(glue::glue(
          ">> All samples in Step {step} completed successfully"
        ))
        self$run_log <- c(
          self$run_log,
          glue::glue(">> All samples in Step {step} completed successfully")
        )
      }

      # Submit checker job
      message(glue::glue(">> [{Sys.time()}] Submitting Step {step} Checker"))
      checker_script <- private$.generate_checker_script(
        step = step,
        workflow_idx = workflow_idx,
        snakemake_condaenv = snakemake_condaenv,
        dryrun = dryrun,
        partition = partition,
        cpus = cpus,
        mem = mem,
        dependency = job_id
      )

      checker_job_id <- private$.submit_sbatch_job(checker_script)
      private$.wait_for_job(checker_job_id)

      return(checker_job_id)
    }
  )
)
