# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Execute rsync over SSH with password authentication
#'
#' This function uses rsync to synchronize files from a remote host to a local destination.
#' It handles password authentication with sshpass and retries the command in case of failure.
#'
#' @param user The username for the remote host.
#' @param host The hostname or IP address of the remote host.
#' @param host_file The path to the file on the remote host to be synchronized.
#' @param dest The local destination path for the synchronized file.
#' @param passwd The password for the remote host.
#'
#' @return NULL
#'
#' @export
beaver_rsync <- function(user, host, host_file, dest, passwd) {
  checkSystemResult <- function(result) {
    # Check if the result is a character and has no 'status' attribute, then return the system output
    if (is.character(result) && is.null(attr(result, "status"))) {
      sys_output <- result
      return(sys_output)
    }

    # If the result is numeric, use it as the status; otherwise, get the 'status' attribute if available
    if (is.numeric(result)) {
      status <- result
    } else {
      status <- if (!is.null(attr(result, "status"))) attr(result, "status") else 0
    }

    # If the status is not 0, print a message indicating command failure
    if (status != 0) message("--Command failed with status: ", status)

    # Return the status
    return(status)
  }

  # Construct the rsync command with sshpass for password authentication
  command <- glue::glue("sshpass -p '{passwd}' rsync --partial --progress --timeout=240 --rsh='ssh -p 2222' '{user}@{host}:{host_file}' {dest}")
  
  # Execute the command and capture the status
  status <- system(command, intern = FALSE, wait = TRUE, ignore.stdout = FALSE, ignore.stderr = FALSE)
  
  # Retry the command if it fails
  while (checkSystemResult(status) != 0) {
    message("--Retrying...")
    status <- system(command, intern = FALSE, wait = TRUE, ignore.stdout = FALSE, ignore.stderr = FALSE)
  }
  
  # Print a success message
  message("OK")
}
