# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Process HTSeq files and generate count and normalized matrices
#'
#' This function processes HTSeq files in the specified directory, extracts gene expression data,
#' and generates both count and normalized matrices. It also performsEntrezeid to Symbol conversion
#' using a provided database and saves the results as text files and RDS files.
#'
#' @param htseq_dir The directory path containing HTSeq files.
#' @param postfix The file postfix to identify relevant HTSeq files.
#' @param output_dir The directory path to save the output files.
#'
#' @return A list containing the count and normalized matrices.
#'
#' @export
beaver_packhtseq <- function(htseq_dir,
                             postfix,
                             output_dir) {
  # List all HTSeq files in the directory with the specified postfix
  htseqfiles <- list.files(path = htseq_dir,
                          pattern = postfix,
                          full.names = TRUE)
  origin_matrix <- NULL
  
  # Process each HTSeq file
  for (i in 1:length(htseqfiles)) {
    sampleid <- stringr::str_remove(htseqfiles[i], pattern = postfix)
    sampleid <- stringr::str_remove(sampleid, pattern = paste0(htseq_dir, "/"))
    message(glue::glue("processing {sampleid}"))
    
    # Read the HTSeq file into a data frame
    temp_df <- readr::read_delim(htseqfiles[i],
                                 delim = "\t", escape_double = FALSE,
                                 col_names = FALSE, col_types = cols(X2 = col_number()),
                                 trim_ws = TRUE)
    colnames(temp_df) <- c("Geneid", sampleid)
    
    # Merge the data frame with the origin matrix
    if (is.null(origin_matrix)) {
      origin_matrix <- temp_df
    } else {
      origin_matrix <- origin_matrix %>%
        dplyr::left_join(temp_df, by = "Geneid")
    }
  }
  
  # Convert Entrezeid to Symbol using the provided database
  message("transforming Entrezeid to Symbol")
  matrix_count <- origin_matrix %>%
    dplyr::right_join(data.frame(Geneid = Entrez_Gene_Id_db$ENSEMBL,
                                 Gene = Entrez_Gene_Id_db$SYMBOL),
                     by = "Geneid") %>%
    dplyr::select(-Geneid) %>%
    dplyr::group_by(Gene) %>%
    dplyr::summarise(across(everything(), ~max(., na.rm = TRUE))) %>%
    dplyr::mutate(row_sum = rowSums(.[, -which(names(.) == "Gene")], na.rm = TRUE)) %>%
    dplyr::filter(row_sum != 0 & row_sum != -Inf & !is.na(row_sum)) %>%
    dplyr::select(-row_sum) %>%
    dplyr::relocate(Gene)
  
  # Save the count matrix as a text file and RDS file
  write.table(matrix_count,
             file = paste0(output_dir, "/matrix_count.txt"),
             row.names = FALSE,
             quote = FALSE)
  saveRDS(matrix_count,
          file = paste0(output_dir, "/matrix_count.RDS"))
  
  # Normalize the count matrix and save it as a text file and RDS file
  matrix_norm <- matrix_count %>% 
    tibble::column_to_rownames("Gene") %>% 
    as.matrix() %>% 
    {
      m <- . + 1
      m <- log2(m)
      m
    } %>% 
    as.data.frame() %>% 
    dplyr::mutate_if(~!is.numeric(.), as.numeric) %>% 
    tibble::rownames_to_column("Gene")
  
  write.table(matrix_norm,
             file = paste0(output_dir, "/matrix_norm.txt"),
             row.names = FALSE,
             quote = FALSE)
  saveRDS(matrix_norm,
          file = paste0(output_dir, "/matrix_norm.RDS"))
  
  # Return a list containing the count and normalized matrices
  return(list(
    count = matrix_count,
    norm = matrix_norm
  ))
}
