# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Convert Methrix object to scMethrix object with optional imputation
#'
#' This function converts a Methrix object to an scMethrix object, optionally performs binning and imputation, and saves the results in HDF5 format.
#' 
#' The function first checks if the HDF5 file already exists in the specified directory. If not, it converts the Methrix object to an scMethrix object.
#' It then performs binning with a specified bin size (default 100,000 bp) and optionally performs imputation using the k-Nearest Neighbors (kNN) method.
#' The results are saved in HDF5 format for efficient storage and retrieval.
#' 
#' @param mdsc_meth A Methrix object containing methylation data.
#' @param impute Logical. Whether to perform imputation on the data. Default is TRUE.
#' @param h5dir Character. The directory where the HDF5 files will be saved. Default is "h5dir".
#' 
#' @return An scMethrix object containing the converted methylation data, optionally binned and imputed.
#' 
#' 
#' @export
beaver_methrix2sc <- function(mdsc_meth,
                              impute = T,
                              h5dir = "h5dir"){
  if (!file.exists(paste0(h5dir,"/assays.h5"))){
    ref_locis <- ref_locis <- mdsc_meth@elementMetadata@listData 
    sse <- SingleCellExperiment::SingleCellExperiment(
      assays = list(
        score = methrix::get_matrix(mdsc_meth, type = "M"),
        counts = methrix::get_matrix(mdsc_meth, type = "C")
      ),
      colData = colData(mdsc_meth) %>% as.data.frame(),
      rowRanges = GRanges(
        seqnames = ref_locis$chr,
        ranges = IRanges(start = ref_locis$start, end = ref_locis$start +1),
        strand = ref_locis$strand
      ),
      metadata = list(
        genome = mdsc_meth@metadata$genome,
        chrom_size = mdsc_meth@metadata$chrom_sizes,
        is_h5 = mdsc_meth@metadata$is_h5
      )
    )
    sse <- scMethrix:::scMethrix(sse)
    message(">> Convert Methrix to scMethrix done!")
    sse <- scMethrix::convert_scMethrix(scm = sse,
                                        h5_dir = h5dir)
    message(">> Convert Methrix to scMethrix with H5 format done!")
  }else{
    sse <- scMethrix::load_HDF5_scMethrix(dir = h5dir)
  }
  
  if (!file.exists(paste0(h5dir,"_bins/assays.h5"))){
    message(">> Calculate Genome bins")
    sse <- scMethrix::bin_scMethrix(sse, 
                                    h5_dir = paste0(h5dir,"_bins"),
                                    bin_size = 100000, 
                                    bin_by = "bp",
                                    n_threads = 40,
                                    replace = T)
    message(">> bins operation done!")
  }else{
    sse <- scMethrix::load_HDF5_scMethrix(dir = paste0(h5dir,"_bins"))
  }
  
  
  if (impute){
    if (!file.exists(paste0(h5dir,"_impute/assays.h5"))){
      message(">> Start imputation")
      sse <- scMethrix::impute_regions(sse, 
                                     assay = "score", 
                                     new_assay = "impute", 
                                     type = "kNN", 
                                     k = 10,
                                     n_threads = 40)
    scMethrix::save_HDF5_scMethrix(scm = sse,
                                 h5_dir = paste0(h5dir,"_impute"),
                                 replace=TRUE)
    }else{
      sse <- scMethrix::load_HDF5_scMethrix(dir = paste0(h5dir,"_impute"))
    }
    
  }
  return(sse)
}
