# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Install and Configure the Beaverflow Workflow Environment
#'
#' This function sets up the Beaverflow workflow environment by creating the necessary directory structure,
#' fetching runtime files, installing required software packages, and configuring the environment.
#' It supports different installation modes based on the detected engine (e.g., Docker, local) and user input.
#'
#' @param workflow_dir The directory where the Beaverflow workflow environment will be installed.
#'   Defaults to the current working directory (`getwd()`).
#' @param enigent The detected engine type. Can be one of "k8s", "container", or other values detected by `beaver_engine_detect()`.
#'   Defaults to the result of `beaver_engine_detect()`.
#' @param build_env install conda envs in the init of the beaverflow, default as False
#' @param build_genome download and compile genome files in the init of the beaverflow, default as False
#' @return NULL
#'
#' @export
#' @details
#' The function performs the following steps:
#' 1. Creates a directory structure under `workflow_dir` with folders such as "config", "data", "envs", etc.
#' 2. Fetches runtime files (e.g., Snakefile) and R scripts from the `xdxtools` package.
#' 3. Installs required software packages using Conda, including Python environments and R packages.
#' 4. Configures the environment based on the detected engine type and user input.
#'
#' If the detected engine is "k8s" or "container", it assumes a pre-built Docker image is used and prompts the user to confirm.
#' If not, it installs Conda environments and R packages locally.
#'
#' Note that this function requires an active internet connection to download and install packages.
#' Additionally, the user may need to download pre-built genomic files from a shared link and place them in the "inst/" directory.
#'
beaverflow_install <- function(workflow_dir = getwd(),
                               enigent = beaver_engine_detect(),
                               build_env = F,
                               build_genome = F){
  whoami <- system(command = "whoami",intern = T)
  message(glue::glue(">> Welcome!{whoami}."))
  message(">> Building Beaverflow dir tree")
  for (i in c("config","data","envs",
              "inst","R","rules",
              "saveRDS","temp","userspace",
              "workflows","www")){
    fs::dir_create(path = paste0(workflow_dir,"/",i))
  }
  message(">> Fetching workflow Runtime")
  fs::file_create(path = paste0(workflow_dir,"/snakefile"))
  message(">> Fetching Rscripts")
  beaver_unpack <- function(src,
                            dest){
    rscripts <- inst_path <- system.file(glue::glue("{src}"), 
                                       package = "xdxtools")
  rscripts_files <- list.files(path = rscripts,
                               full.names = F)
  package_rfiles <- paste0(rscripts,"/",rscripts_files)
  if(is.null(dest)){
    workflow_rfiles <- paste0(workflow_dir,"/",rscripts_files)
  }else{
    workflow_rfiles <- paste0(workflow_dir,"/",dest,"/",rscripts_files)
  }
  
  for (i in 1:length(package_rfiles)){
    fs::file_copy(path = package_rfiles[i],
                  new_path = workflow_rfiles[i],
                  overwrite = T)
  }
  }
  beaver_unpack(src = "Rscripts",
                dest = "R")
  
  beaver_unpack(src = "snakefiles",
                dest = NULL)
  
  if (enigent %in% c("k8s","container")){
    answer <- "unknow"
    while(!(answer %in% c("1","2"))){
      message(">> We assume you are using the pre-build docker image :")
      message("1.yup")
      message("2.No")
      answer <- readline("Input your answer [1|2] >> ")
      if (answer == "1"){
        type <- "root"
      } else if(answer == "2"){
        type <- "rootless"
        }else{
          message(">> Only 1 and 2 is allow,please retry.")
          }
    }
    }else{
    type <- "rootless"
  }
  
  beaver_unpack(src = paste0(type,"_rules"),
                dest = "rules")
  
  beaver_unpack(src = "workflows",
                dest = "workflows")
  
  message(">> Building Run-Mode environment")
  
  if (type == "root"){
    
    message(">> All needed packages have been pre-installed in the docker image")
    
  }else{
    # add build_env param here
    
    message(">> Check miniconda ...")
    
    condaType <- readline("What is your TYPE of conda installed ? [miniconda3|micromamba] >> ")
    
    if (grepl("mamba",condaType)){
      conda_call <- "alias conda=mamba && conda"
      message(">> Warning,Please alias mamba to conda in .bashrc to avoid errors in using beaverflow.")
    }else if(grepl("conda",condaType)){
      conda_call <- "conda"
    }else{
      stop(">> please input a correct conda version")
    }
  
    conda_try <- try(system(command = glue::glue("export PATH={Sys.getenv('HOME')}/{condaType}/bin:$PATH && {conda_call} env list"),
                            intern = T))
    
    if (class(conda_try) == "try-error"){
      message(">> Sad!Conda is required and 'PATH=$HOME/path_to_conda/bin:$PATH' should be added to .bashrc")
      answer2 <- "unknow"
      while (answer2 == "unknow") {
        answer2 <- readline("Install miniconda and set PATH for me >> [yes|no]")
        if (!(answer2 %in% c("yes","no"))) answer2 <- "unknow"
      }
      if (answer2 == "yes"){
        conda_install <- system.file("install_script/miniconda_install.sh",
                                    package = "xdxtools")
        conda_script <- glue::glue("chmod +x {conda_install } && bash {conda_install } ")
        system(command = conda_script )
      }else{
        stop(">> Exit.")
      }
      
    }else{
      message(">> Good News! you seems to have a conda version READY to be used. ")
    }
      command_script <- system.file("install_script/beaverConda_pak_install.sh",
                                    package = "xdxtools")
      
      run_script <- glue::glue("export PATH={Sys.getenv('HOME')}/{condaType}/bin:$PATH && chmod +x {command_script} && bash {command_script} ")
      
      if (conda_call != "conda") run_script <- paste("alias conda=mamba &&",                                        
                                                     run_script)
      
      if (build_env){
        message(">> Installing Conda envs and R packages ...")
        system(command = run_script)
      }
    
  }
  if (build_genome){
    message(">> Download Genomic files")
    human_version <- "none"
    while (!(human_version %in% c("hg19","hg38"))) {
      human_version <- readline("Building human genome [hg19|hg38] >> ")
    }
    mouse_version <- "none"
    while (!(mouse_version %in% c("mm10","mm39"))) {
      mouse_version <- readline("Building mouse genome [mm10|mm39] >> ")
    }
    
    download_human <- glue::glue("wget -P inst/pdx/homo_sapiens/ https://hgdownload.soe.ucsc.edu/goldenPath/{human_version}/bigZips/{human_version}.fa.gz")
    download_mouse <- glue::glue("wget -P inst/pdx/mouse/ https://hgdownload.soe.ucsc.edu/goldenPath/{mouse_version}/bigZips/{mouse_version}.fa.gz")
    download_human_gtf <- glue::glue("wget -P inst/rnaseq/homo_sapiens/ https://hgdownload.soe.ucsc.edu/goldenPath/{human_version}/bigZips/genes/{human_version}.ensGene.gtf.gz")
    fs::dir_create("inst/pdx/homo_sapiens/")
    fs::dir_create("inst/pdx/mouse/")
    fs::dir_create("inst/rnaseq/homo_sapiens/")
    system(command = download_human)
    system(command = download_mouse)
    message(">> building Genomic files")
    system(command = glue::glue("gunzip inst/pdx/homo_sapiens/{human_version}.fa.gz"))
    system(command = glue::glue("gunzip inst/rnaseq/homo_sapiens/{human_version}.ensGene.gtf.gz"))
    build_script <- system.file("install_script/build_genome.sh",
                                package = "xdxtools")
    build_genome_command <- glue::glue("sed -i 's/hg38/{human_version}/g' {build_script} && chmod +x {build_script} && sbatch {build_script}")
    system(command = build_genome_command)
  }else{
    message(">> Fetching Genomic files")
    message(">>> You need to download pre-build Genomic files through our shared link:https://pan.quark.cn/s/e0908b382183")
  message(">>> please place these files under the dir : inst/")
  message(">>> or a self-build of bismark/STAR-required refer Genome is suggested.")
  }
  
  message(">>> Congratulations! we hope to share you with the enjoyment of the R6-OOP BeaverGandalf,and,")
  message(glue::glue(">>> You're a very fine person, Dear {whoami}. 
                     And I'm very fond of you. 
                     But we're only quite little fellows...in a wide world after all."))
  
}


