# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Perform Conflict Network Analysis for Pathway-Specific Methylation
#'
#' This function analyzes the conflict between hyper- and hypo-methylated genes within a specified pathway,
#' constructs a gene network based on the pathway's edge list, and visualizes the network with node annotations.
#'
#' The function performs the following steps:
#' 1. Identifies hyper- and hypo-methylated genes from the input data frame.
#' 2. Filters genes based on the specified pathway.
#' 3. Maps genes to their Entrez IDs and annotates them with methylation direction (hyper, hypo, or bidirectional).
#' 4. Constructs a subgraph of the pathway's gene network using the filtered genes.
#' 5. Visualizes the network with nodes colored by methylation direction and labeled with gene symbols.
#'
#' @param df Data frame. The input data frame containing methylation results.
#'           Expected columns include "Term" (or "term_name") and "Genes" (or "overlapping_genes").
#' @param pathway Character vector. The pathway term(s) to filter the genes.
#' @param edgelist Data frame. The edge list of the pathway's gene network.
#'                 Expected columns include "from" and "to" for gene interactions.
#' @param graph_layout Character. The layout algorithm for plotting the network. Default is "graphopt".
#'
#' @return A list containing:
#'   - `overlap`: A list with hyper-, hypo-, and intersecting genes.
#'   - `graph`: The igraph object representing the gene network.
#'   - `ggraph`: The ggraph plot object of the network.
#'
#' @details
#' This function assumes that the input data frame `df` contains columns for pathway terms and gene lists.
#' The `edgelist` should be a data frame representing the gene interactions within the pathway.
#' @export
conflict_network_analysis <- function(df,
                                      pathway,
                                      edgelist ,
                                      graph_layout = 'graphopt'){
  message(">> Check colnames ...")
  if("Term" %in% colnames(df)){
    term <- "Term"
  }else{
    term <- "term_name"
  }
  
  if ("Genes" %in% colnames(df)){
    gene <- "Genes"
  }else{
    gene <- "overlapping_genes"
  }
  message(">> Decode genes ...")
  hsc_2ne_overlap <- df %>% 
    dplyr::filter(.[[term]] %in% pathway) %>% 
    {
      temp <- .
      message(">> hyper methylation Genes are :")
      hyper <- temp %>% 
        dplyr::filter(direction == "hyper")
      print(hyper[[gene]])
      hyper <- hyper[[gene]] %>% 
        stringr::str_split(.,";")
      message(">> hypo methylation Genes are :")
      hypo <- temp %>% 
        dplyr::filter(direction == "hypo")
      print(hypo[[gene]])
      hypo <- hypo[[gene]] %>% 
        stringr::str_split(.,";")
      message(">> check intersect genes are :")
      print(intersect(hyper[[1]],hypo[[1]]))
      list(
        hyper = hyper[[1]],
        hypo = hypo[[1]],
        intersect = intersect(hyper[[1]],hypo[[1]])
      )
    }
  
  # plot Rap1 signaling pathway subnet,出一个id+symbol+hyper/hypo标签
  hsc_2ne_overlap_id <- hsc_2ne_overlap %>% 
    {
      temp <- .
      message(">> Processing hyper gene")
      hyperid <- Entrez_Gene_Id_db %>% 
        dplyr::filter(SYMBOL %in% temp$hyper) %>% 
        dplyr::mutate(direction = "hyper")
      message(">> Processing hypo gene")
      hypoid <- Entrez_Gene_Id_db %>% 
        dplyr::filter(SYMBOL %in% temp$hypo)%>% 
        dplyr::mutate(direction = "hypo")
      combine1 <- rbind(hypoid,hyperid) %>% 
        dplyr::filter(!(SYMBOL %in% temp$intersect))
      combine_patch <- rbind(hypoid,hyperid) %>% 
        dplyr::filter(SYMBOL %in% temp$intersect) %>% 
        dplyr::distinct(SYMBOL,.keep_all = T) %>% 
        dplyr::mutate(direction = "bisdirection")
      rbind(combine1,combine_patch)
    } %>% 
    as.data.frame()
  
  message(">> Make graphes ...")
  library(igraph)
  temp_graph <- edgelist %>% 
    dplyr::filter(!is.na(.data[["from"]])) %>% 
    dplyr::filter(!is.na(.data[["to"]]))
  temp_graph <- temp_graph %>% 
    igraph::graph_from_data_frame() %>% 
    igraph::simplify() 
  message(">> Subset graphes by genes:")
  subset_vid <- intersect(V(temp_graph)$name,
                          as.character(unlist(hsc_2ne_overlap_id[["ENTREZID"]]))
  )
  #print(str(hsc_2ne_overlap_id))
  #print(head(V(temp_graph)$name))
  print(glue::glue("{length(subset_vid)}/{nrow(hsc_2ne_overlap_id)}"))
  print(subset_vid)
  temp_graph <- igraph::induced.subgraph(temp_graph,
                             vids = subset_vid) 
  # 注释
  message(">> Create graph done!")
  Rap1_graph_node_annote <- data.frame(ENTREZID = V(temp_graph)$name) %>% 
    dplyr::left_join(dplyr::mutate(hsc_2ne_overlap_id,ENTREZID =as.character(ENTREZID)),
                     by = "ENTREZID") %>% 
    distinct(ENTREZID,.keep_all = T)
  
  temp_graph <- igraph::set_vertex_attr(temp_graph,
                                        name = "symbol",
                                        value = Rap1_graph_node_annote$SYMBOL)
  temp_graph <- igraph::set_vertex_attr(temp_graph,
                                        name = "direction",
                                        value = Rap1_graph_node_annote$direction)
  
  # plot genetic network 
  message(">> Plotting ...")
  library(ggraph)
  p <- ggraph(temp_graph, layout = graph_layout) +
    geom_edge_link(arrow = arrow(length = unit(4, 'mm')),
                   end_cap = circle(2, 'mm')) +
    geom_node_point(aes(fill = direction, colour = direction),size = 8) +
    geom_node_text(aes(label = symbol), repel = TRUE) +
    coord_fixed() +
    theme_graph(base_family="sans")
  print(p)
  return(list(
    overlap = hsc_2ne_overlap,
    graph = temp_graph,
    ggraph = p
  ))
}
