# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Aggregate and Compress Files in a Directory
#'
#' This function aggregates all files within a specified directory (including subdirectories) and compresses them into a single archive file.
#' The function returns a list containing the root path, a data frame with file information, and the path to the compressed file.
#'
#' @param path \code{character} The root directory path to search for files.
#' @param method \code{character} The compression method to use. Options are \code{"gzip"} for \code{.tar.gz} compression or \code{"zip"} for \code{.zip} compression. Default is \code{"gzip"}.
#' @return A list with the following components:
#'   \item{rootpath}{The root directory path.}
#'   \item{filedf}{A data frame containing two columns: \code{name} (file names) and \code{filepath} (full paths of the files).}
#'   \item{compressfile}{The path to the compressed file.}
#' @note If no files are found in the specified directory, an empty data frame is returned.
#' @examples
#' # Example usage:
#' result <- file_agg(path = "/path/to/directory", method = "zip")
#' print(result$compressfile)
#'
#' # Example with gzip compression:
#' result <- file_agg(path = "/path/to/directory", method = "gzip")
#' print(result$compressfile)
#'
#'
#' @export
file_agg <- function(path, method = c("gzip", "zip")) {
  
  files <- list.files(path = path,
                      full.names = TRUE,
                      recursive = TRUE)
  if (length(files) == 0) {
    return(data.frame())
  } else {
    filenames <- basename(files)
    df <- data.frame(
      name = filenames,
      filepath = files
    )
    message(">> Compress files")
    if (method == "zip") {
      zip(zipfile = paste0(path, "/result.zip"),
          files = files)
      gzfile = paste0(path, "/result.zip")
    } else {
      tar(tarfile = paste0(path, "/result.tar.gz"),
          files = files,
          compression = "gzip")
      gzfile = paste0(path, "/result.tar.gz")  # Fix incorrect assignment
    }
    return(
      list(
        rootpath = path,
        filedf = df,
        compressfile = gzfile
      )
    )
  }
}
