# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' detect mem
#' 
#' detect memory usage in current session
#' 
#' @return memory usage
#' 
#' @export
mem_detect <- function(){
  mem <- ps::ps_memory_full_info()
  mem <- mem["rss"]/1024/1024
  return(mem)
}
