# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Reverse complement a DNA sequence or vector of DNA sequences
#'
#' This function takes a DNA sequence or a vector of DNA sequences and returns their reverse complements.
#' It converts the input to uppercase, uses a lookup table to replace each nucleotide with its complement,
#' and then reverses the resulting string.
#'
#' @param strings A single DNA sequence or a vector of DNA sequences to be reverse complemented.
#'
#' @return A character vector with the reverse complements of the input sequences.
#'
#' @export
revCompString <- function(strings){
  
  toupper <- function (x) {
    if (!is.character(x)) 
      x <- as.character(x)
    .Internal(toupper(x))
  }
  revString <- function(strings){
    
    strings = as.character(strings)
    res = as.character(lapply(strings, function(x) paste(rev(strsplit(x, "")[[1]]), collapse = "")))
    return(res)
  }
  
  if (is.na(strings) | is.null(strings) | strings == ""){
    return("")
  }else{
    strings = toupper(strings)	
    idx = data.frame(to = c("T", "C", "G", "A", "N"), row.names = c("A", "G", "C", "T", "N"))
    res = as.character(sapply(strings, function(x) revString(paste(as.character(idx[strsplit(x, "")[[1]], "to"]), collapse = ""))))
    # chars = strsplit(strings, "")[[1]]
     # res = revString(paste(as.character(idx[chars, "to"]), collapse = ""))
    return(res)
  }
}
