# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Update and Reinitialize a BeaverGandalf Object
#'
#' This function creates a new instance of the \code{BeaverGandalf} class based on
#' an existing object (\code{gandalfthegray}). It retains the original configuration
#' parameters but allows for updates or modifications as needed. This is useful for
#' reinitializing the workflow with the same settings or adjusting specific parameters.
#'
#' @param gandalfthegray An existing \code{BeaverGandalf} object to be updated.
#' @return A new \code{BeaverGandalf} object (\code{gandalfthewhite}) with the updated configuration.
#'
#' @details
#' - The function extracts key parameters from the existing \code{gandalfthegray} object,
#'   including mode, species, uploaded files, phenotype data, workflow endpoint, user email,
#'   and user ID.
#' - It initializes a new \code{BeaverGandalf} object with these parameters.
#' - The \code{new_userid_always} parameter is set to \code{FALSE} to reuse the existing user ID.
#' - This function is useful for restarting or updating the workflow while preserving the original settings.
#' @export
update_gandalf <- function(gandalfthegray){
  gandalfthewhite <- BeaverGandalf$new(
    Mode = gandalfthegray$Mode,
    species1 = gandalfthegray$species1,
    species2 = gandalfthegray$species2,
    uploadfile = gandalfthegray$uploadfile, # 是一个表格，由上传功能自动生成
    pdata = gandalfthegray$pdata, # 是一个表格（上传送样表，需要sampleid和inline_barcode_...两列）
    workflow_endpoint = as.character(sum(gandalfthegray$workflow_endpoint)), # pipeline 的终点，从前端输入
    user_email = gandalfthegray$user_email,
    new_userid_always = F,
    userid = gandalfthegray$userid
  )
  return(gandalfthewhite)
}
