# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Retrieve pdata file path based on upload status and server path
#'
#' This function determines the source of pdata based on whether an upload file is provided and whether a server path exists.
#' If an upload file is present, it returns the upload file. If the server path does not exist, it returns a "notfound" message.
#' Otherwise, it returns a list containing the server path to the pdata file.
#'
#' @param uploadfile The uploaded pdata file object.
#' @param serverpath The path to the server directory where the pdata file might be stored.
#'
#' @return Either the uploaded pdata file object, a "notfound" message, or a list containing the server path to the pdata file.
#'
#' @export
use_server_pdata <- function(uploadfile = NULL,
                             serverpath){
  uploadstatus <- is.null(uploadfile)
  serverstatus <- file.exists(serverpath)
  if (!uploadstatus){
    filepath <- uploadfile$filepath
  }else if(!serverstatus){
    filepath = "notfound"
  }else{
    filepath = serverpath
  }
  if (filepath != "notfound"){
    data <- readxl::read_excel(path = serverpath)
    if ("样本编号" %in% colnames(data)){
      colnames(data)[4] <- "sampleid"
      colnames(data)[7] <- "inline_barcode_sequence"
    }
    return(data)
  }else{
    return(data.frame())
  }
}
