# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Check the status of uploaded files and server path, and return relevant information
#'
#' This function checks whether an uploaded file is provided and whether a server path exists.
#' If an uploaded file is present, it returns the file. If the server path does not exist, it returns
#' a "notfound" message. Otherwise, it lists the fastq files in the server path and returns a data frame
#' with the file names and paths.
#'
#' @param uploadfile The uploaded file object.
#' @param serverpath The path to the server directory containing fastq files.
#'
#' @return Either the uploaded file object, a "notfound" message, or a data frame with fastq file names and paths.
#'
#' @export
use_sever_fastq <- function(uploadfile = NULL,
                            serverpath){
  uploadstatus <- is.null(uploadfile)
  serverstatus <- dir.exists(serverpath)
  if (!uploadstatus){
    return(uploadfile)
  }else if(!serverstatus){
    return(data.frame(name = "NA",filepath = "NA"))
  }else{
    fastqfilespath <- list.files(serverpath,full.names = T)
    fastqfilename <- list.files(serverpath,full.names = F)
    df <- data.frame(
      name = fastqfilename,
      filepath = fastqfilespath
    )
    return(df)
  }
}
